Move support documents to a separate hierarchy
sailfishos/docs.sailfishos.org pull request #116
Opened 2022-09-21 12:00 UTC by vigejolla

Signed-off-by: Ville Nummela <ville.nummela@jolla.com>

2022-09-21 12:13 UTC, jovirkku commented
Where would the help articles (from Zendesk) reside? In Support/SupportedDevices or would there also be Support/SupportArticles (or Support/BestPractices)?

2022-09-21 12:20 UTC, jpwalden approved these changes
LGTM

2022-09-21 12:57 UTC, jovirkku commented
This comment is not directly about this PR but not far-fetched. There will soon be new folders under Support.

A naming convention is needed. We have folder names "Known_Issues" and "SupportedDevices". Should we use the underscore style or not?

2022-09-21 12:58 UTC, jovirkku approved these changes
It would be good to agree on a naming convention.
We have now "Known_Issues" (with underscore) and "SupportedDevices"

Adding the Support sections looks ok to me.

2022-09-21 20:45 UTC, sledges requested changes

2022-09-21 20:45 UTC, sledges commented on Support/Releases/Known_Issues/README.md
>  title: Known issues in OS releases
This is already shown under the "Releases" parent:
```suggestion
title: Known issues
```

2022-09-21 20:45 UTC, sledges commented on index.md
> +  <a href="/Support/SupportedDevices">
Note for future: when the `Support` section gets more and more sub-pages as time goes by, it will make sense to be able to access `/Support` itself from the landing page.

2022-09-21 20:45 UTC, sledges commented on _config.yml
> +    - "/Support"
This new item is cut off when viewed in landscape Sailfish Browser on Xperia 10 III. This CSS needs tweaking: https://github.com/sailfishos/docs.sailfishos.org/blob/44b68baf0973036030d757af0d44cae8fba79521/assets/css/just-the-docs-sfos.scss#L82

2022-09-21 20:47 UTC, sledges commented
> It would be good to agree on a naming convention.
> We have now "Known_Issues" (with underscore) and "SupportedDevices"

All pages in this documentation have been migrated from old wiki named `Like_This`, not `LikeThis`.
When `SupportedDevices` was added, it wasn't paying attention as to what the whole docs source convention is:)

2022-09-22 04:07 UTC, vigejolla commented on index.md
> +  <a href="/Support/SupportedDevices">
I agree. But we'll need a bit more content on the "Support" page before that.

2022-09-22 05:06 UTC, vigejolla commented on _config.yml
> +    - "/Support"
Tweaked slightly. The padding is now slightly smaller on Xperia 10 III.

2022-09-22 05:06 UTC, vigejolla commented
> When SupportedDevices was added, it wasn't paying attention as to what the whole docs source convention is:)

Now was a good time to rename that to Supported_Devices, so I did just that

2022-09-22 05:22 UTC, sledges commented on index.md
> +  <a href="/Support/SupportedDevices">
```suggestion
  <a href="/Support/Supported_Devices">
```

2022-09-22 05:26 UTC, sledges commented on Support/Releases/Known_Issues/README.md
> +title: Known issues
nit I missed:
```suggestion
title: Known Issues
```

2022-09-22 05:40 UTC, sledges approved these changes

2022-09-22 05:41 UTC, merged