Creating Help Articles folder
sailfishos/docs.sailfishos.org pull request #123
Opened 2022-09-27 08:45 UTC by jpwalden

Signed-off-by: jari-pekka walden <jari-pekka.walden@jolla.com>

2022-09-27 08:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sailfishos/docs.sailfishos.org?pullRequest=123) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sailfishos/docs.sailfishos.org?pullRequest=123) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sailfishos/docs.sailfishos.org?pullRequest=123) it.</sub>

2022-09-27 08:53 UTC, vigejolla requested changes

2022-09-27 08:53 UTC, vigejolla commented on Support/Help_Articles/README.md
> +nav_order: 100
We now have same nav_order on Releases/README.md as well. It should be something different, I suggest 150 if we want to have this page between Releases and Supported Devices

2022-09-27 08:57 UTC, vigejolla commented
I don't fully see how this PR maps to the task 58506, are you sure the bug number in the branch name is correct?

On a related note, I don't think it makes sense to merge this PR without any "subpages". So, if your intention was indeed to add the page mentioned in task 58506 here, I suggest you add it in this same PR.

2022-09-27 09:02 UTC, jpwalden commented
> I don't fully see how this PR maps to the task 58506, are you sure the bug number in the branch name is correct?
> 
> On a related note, I don't think it makes sense to merge this PR without any "subpages". So, if your intention was indeed to add the page mentioned in task 58506 here, I suggest you add it in this same PR.

Yes, the intention was to add that ZD article, creating of the folder is the 1st step, therefore we used that ID.

2022-09-28 06:19 UTC, vigejolla commented
Please squash the commits

2022-09-28 12:04 UTC, vigejolla approved these changes
LGTM, but please don't merge this before you have some content for the folder as well

2022-09-28 13:31 UTC, jovirkku commented
The created folder Support/Help_Articles will contain plenty of subfolders, each for one help article.

2022-10-03 06:40 UTC, jovirkku requested changes
Line 142 in README.md: the code has "Sailfish-dir-content-3.1.0.11.PNG" while the picture has the extension .png ==> the picture is not shown in chapter 4 (picture 4b).

Line 104 has "...with Android O****S."

Chapter 4: "...is always available in [this repository](https://shop.jolla.com/downloads/) [*]"
As that sentence has the hyperlink then perhaps the "[*]" and the later (two lines down) URL are not necessary.

The header numbers, then. I think this DOC service has an automatic TOC and numbering of headers. The manually written numbers might lead to duplicate numbering. Not sure, though. 

Otherwise, it looks good.

2022-10-10 09:39 UTC, vigejolla requested changes
Please fix also those findings from @jovirkku

2022-10-10 09:39 UTC, vigejolla commented on Support/Help_Articles/Installing_Sailfish/README.md
> +parent: Help_Articles
```suggestion
parent: Help Articles
```

parent should have the title of the parent page, not directory name

2022-10-10 09:39 UTC, vigejolla commented on Support/Help_Articles/Installing_Sailfish/README.md
> +title: Reinstalling Sailfish OS
I would prefer having title identical to the directory name (not counting the ' ' vs '_' difference). So I would suggest you change either the title to "Installing Sailfish" or change the directory name to "Reinstalling_Sailfish_OS". In my opinion the latter is the better option.

2022-10-11 08:39 UTC, jpwalden commented on Support/Help_Articles/Installing_Sailfish/README.md
> +parent: Help_Articles
Done

2022-10-11 08:39 UTC, jpwalden commented on Support/Help_Articles/Installing_Sailfish/README.md
> +title: Reinstalling Sailfish OS
Directory name changed to Reinstalling_Sailfish_OS

2022-10-11 09:03 UTC, vigejolla approved these changes
LGTM

2022-10-11 09:04 UTC, merged