Tips and tricks
sailfishos/docs.sailfishos.org pull request #126
Opened 2022-10-04 10:57 UTC by jovirkku

Several ZD articles combined into Tips and Tricks. JB#58163.

2022-10-04 11:40 UTC, jpwalden reviewed
These sound little bit odd, but very minor (line 73):
"Should you receive an error about an incorrect password or username.."
Could be: "If you receive an error.."
same with (line 333) "Should you have problems with installing.."
Could be "If you have problems.."

Some of the links are not functional:
Lines: 246, 320, 371, 377

Otherwise looks good to me.

2022-10-04 11:50 UTC, spiiroin commented on Support/Help_Articles/Tips_and_Tricks/README.md
> +1.  Press both the Power and the Volume Up keys down at the same time and keep them pressed.
Does this like this work for all currently supported devices? (e.g. in n9 or n900 it was enough just to keep power key pressed for 7 seconds or stte, but maybe some sort of "industry standard" has risen since those days?)

2022-10-04 14:58 UTC, jovirkku commented on Support/Help_Articles/Tips_and_Tricks/README.md
> +1.  Press both the Power and the Volume Up keys down at the same time and keep them pressed.
It appears to work on all Xperia phones we support.

2022-10-05 06:03 UTC, spiiroin commented on Support/Help_Articles/Tips_and_Tricks/README.md
> +1.  Press both the Power and the Volume Up keys down at the same time and keep them pressed.
To me the text just sounds a bit too definite since there is some variance & we do provide device specific instructions elsewhere. On a quick search android boards seem to use language to the effect of: "most devices power+vol down; some power + both vol keys; rare instances something else". Does not matter if it works as described all devices we expect people to use, but might be worthwhile to name few models where we know this info to be true? (but I'll leave it up to you to decide whether it is worthwhile, it is just fine as it is)

2022-10-05 13:15 UTC, jovirkku commented on Support/Help_Articles/Tips_and_Tricks/README.md
> +1.  Press both the Power and the Volume Up keys down at the same time and keep them pressed.
I have successfully used that for years in my Care tasks. Many customers have been helped with that advice.
I tried it now on Xperia 10 III, Xperia 10 II, Xperia XA2, and Xperia X. I was not able to force those phones to an abnormal state but, instead, pressing the keys at the security code prompt led to those 3 plays of the vibrator, after which the phones are off. At least Xperia 10 III and II do not play the triple vibra sequence if Power + VolDown are pressed.
I trust on my sentence.

2022-10-10 08:52 UTC, spiiroin approved these changes
My concerns were addressed.

2022-10-11 09:15 UTC, vigejolla commented
please rebase on top of master

2022-10-11 09:27 UTC, vigejolla commented on Support/Help_Articles/Tips_and_Tricks/README.md
> +nav_order: 1000
missing parent

2022-10-11 09:28 UTC, vigejolla commented on Support/Help_Articles/Tips_and_Tricks/README.md
> +has_children: true
no, this document does not have children

2022-10-11 09:32 UTC, vigejolla commented on Support/Help_Articles/Tips_and_Tricks/README.md
> +|-|
Not sure what you are trying to accomplish here but it clearly isn't working

2022-10-11 09:35 UTC, vigejolla requested changes
Some issues need fixing before this can be merged

2022-10-11 10:07 UTC, vigejolla commented on Support/Help_Articles/Tips_and_Tricks/README.md
> +permalink: Support/Help_Articles/Tips_and_Tricks
```suggestion
permalink: Support/Help_Articles/Tips_and_Tricks/
```

2022-10-11 10:41 UTC, jovirkku commented on Support/Help_Articles/Tips_and_Tricks/README.md
> +permalink: Support/Help_Articles/Tips_and_Tricks
Slash added.

2022-10-11 10:43 UTC, jovirkku commented on Support/Help_Articles/Tips_and_Tricks/README.md
> +|-|
Inserting pictures into 3x1 tables fixed. The main declaration must be on one row (from <a href to </a>).

2022-10-11 10:47 UTC, jovirkku commented
Done so far:
- title added
- parent added
- children removed
- slash added to the end of permalink
(I list the changes here as I cannot find how to handle the "unresolved conversations", some of which have "outdated")

2022-10-11 12:06 UTC, merged