Testing advice page
sailfishos/docs.sailfishos.org pull request #136
Opened 2022-10-12 12:28 UTC by jpwalden

Signed-off-by: jari-pekka walden <jari-pekka.walden@jolla.com>

2022-10-13 04:49 UTC, vigejolla commented on Develop/Platform/testing_advice/README.md
> +permalink: Develop/Platform/testing_advice/
Please use Capital first letter in directory name

2022-10-13 04:52 UTC, vigejolla commented on Develop/Platform/testing_advice/README.md
> +nav_order: 150
It has been our custom to use full hundreds unless adding a page between two already existing pages

2022-10-13 04:58 UTC, vigejolla commented on Develop/Platform/testing_advice/README.md
> +has_children: true
Should be false as this page does not have children

2022-10-13 04:58 UTC, vigejolla commented on Develop/Platform/testing_advice/README.md
> +#Testing in general
Missing space between # and T

2022-10-13 04:59 UTC, vigejolla commented on Develop/Platform/testing_advice/README.md
> +#Testing in general
same for all headings

2022-10-13 05:02 UTC, vigejolla commented on Develop/Platform/testing_advice/README.md
> +```nosh
No need for `nosh` here. It's only used for shell script snippets in order to disable code highlighting for those. The reason for that is that the code highlighting doesn't quite do what we would like it to do on shell scripts.

2022-10-13 06:57 UTC, jovirkku requested changes

2022-10-13 06:57 UTC, jovirkku commented on Develop/Platform/testing_advice/README.md
> +When evaluating the found bug it is important to make sure that the bug is valid, good way is to test if the bug is visible with another device (if available), also reference device testing gives val
depeneds > depends

2022-10-13 06:57 UTC, jovirkku commented on Develop/Platform/testing_advice/README.md
> +On some areas journal logs are not enough to reveal the root cause and there fore additional logs might be needed.
there fore > therefore

2022-10-13 07:05 UTC, jovirkku commented on Develop/Platform/testing_advice/README.md
> +Testing is started as soon as the basic functionality of the feature is in place. Preferably before the code is merged to devel and testing will be continued when the code is in devel.
I wonder if this is clear for an external reader. Especially, what is 'devel'. Should there be a short description of our development lifecycle, or at least explain that 'devel' means the development codebase (or branch?)  to which developers merge their work? Secondly, I wonder how a feature can be tested before it is in 'devel'. Would the tester work in the developer's environment (or in the copy of that)?

2022-10-13 07:35 UTC, jovirkku commented on Develop/Platform/testing_advice/README.md
> +When providing logs at least journal logs (https://jolla.zendesk.com/hc/en-us/articles/202886373) should be provided
"It's good practice to surround URLs: <http://some.url>"
(quoting from https://github.com/sailfishos/docs.sailfishos.org/#sailfish-os-documentation)

2022-10-13 12:23 UTC, jpwalden commented on Develop/Platform/testing_advice/README.md
> +permalink: Develop/Platform/testing_advice/
Corrected

2022-10-13 12:23 UTC, jpwalden commented on Develop/Platform/testing_advice/README.md
> +nav_order: 150
Changed to 200

2022-10-13 12:23 UTC, jpwalden commented on Develop/Platform/testing_advice/README.md
> +has_children: true
Corrected

2022-10-13 12:24 UTC, jpwalden commented on Develop/Platform/testing_advice/README.md
> +#Testing in general
Corrected

2022-10-13 12:24 UTC, jpwalden commented on Develop/Platform/testing_advice/README.md
> +```nosh
Removed

2022-10-13 12:24 UTC, jpwalden commented on Develop/Platform/testing_advice/README.md
> +When evaluating the found bug it is important to make sure that the bug is valid, good way is to test if the bug is visible with another device (if available), also reference device testing gives val
Corrected

2022-10-13 12:24 UTC, jpwalden commented on Develop/Platform/testing_advice/README.md
> +On some areas journal logs are not enough to reveal the root cause and there fore additional logs might be needed.
Corrected

2022-10-13 12:26 UTC, jpwalden commented on Develop/Platform/testing_advice/README.md
> +Testing is started as soon as the basic functionality of the feature is in place. Preferably before the code is merged to devel and testing will be continued when the code is in devel.
Didn't change this at least yet. Added more content on the log part mainly from the https://forum.sailfishos.org/t/wiki-collecting-debug-information/12751

2022-10-14 09:24 UTC, vigejolla commented on Develop/Platform/Testing_Advice/README.md
> +[This content is copied from forum](https://forum.sailfishos.org/t/wiki-collecting-debug-information/12751)
I think we can leave this bit out from the page, as the reader is probably not that interested where the information is from. I would instead mention that in the commit message.

2022-10-14 09:31 UTC, vigejolla commented
To me this looks good, but I'll give @jovirkku a chance to verify himself that his concerns have been addressed. Please rebase on top of master.

2022-10-14 10:36 UTC, jovirkku approved these changes
Looks ok to me.

2022-10-14 11:24 UTC, vigejolla approved these changes

2022-10-14 11:24 UTC, merged