Updating Sailfish OS
sailfishos/docs.sailfishos.org pull request #137
Opened 2022-10-12 14:03 UTC by jovirkku

Signed-off-by: Jorma Virkkunen <jorma.virkkunen@jolla.com>

2022-10-12 14:55 UTC, jovirkku commented
Please review now.

2022-10-13 06:05 UTC, vigejolla commented on Support/Help_Articles/Updating_OS/README.md
> +nav_order: 90
Why 90? I would have picked 50, but perhaps you have a plan about other pages to be added here.

2022-10-13 06:06 UTC, vigejolla commented on Support/Help_Articles/Updating_OS/README.md
> +permalink: Support/Help_Articles/Updating_OS/
Let's try to keep the titles and directory names identical, it makes it easier to find the pages in the tree

2022-10-13 07:23 UTC, jovirkku commented on Support/Help_Articles/Updating_OS/README.md
> +permalink: Support/Help_Articles/Updating_OS/
My idea was that while the permalink should be fairly compact, the title could be more verbose.

2022-10-13 07:24 UTC, jovirkku commented on Support/Help_Articles/Updating_OS/README.md
> +nav_order: 90
50 would be better. Leave room for more documents (in alphabetical order if we want that)

2022-10-13 09:56 UTC, vigejolla commented on Support/Help_Articles/Updating_OS/README.md
> +permalink: Support/Help_Articles/Updating_OS/
There's no reason for keeping the permalinks a.k.a. directory names compact. See e.g. [Upstream_Git_with_Long-Lived_Topic_Branch_Approach](https://github.com/sailfishos/docs.sailfishos.org/blob/master/Develop/Platform/Usage_of_packaging_formats/Upstream_Git_with_Long-Lived_Topic_Branch_Approach/README.md?plain=1#L3) for an example of a fairly long permalink. That being said, I think "Updating Sailfish OS" would be a good middleground.

2022-10-13 14:57 UTC, jovirkku commented on Support/Help_Articles/Updating_OS/README.md
> +nav_order: 90
permalink: Support/Help_Articles/Updating_Sailfish_OS/
nav_order: 150   (alphabetical order)

Done.

2022-10-13 14:57 UTC, jovirkku commented on Support/Help_Articles/Updating_OS/README.md
> +permalink: Support/Help_Articles/Updating_OS/
New title: Updating Sailfish OS

2022-10-13 14:59 UTC, jovirkku commented
The new framework for the pictures is waiting for the instructions.

2022-10-13 22:04 UTC, sledges requested changes
Small bits, most can be corrected when migrating to #138.

2022-10-13 22:04 UTC, sledges commented on Support/Help_Articles/Updating_Sailfish_OS/README.md
> +|<a href="OS-could-not-be-updated-reboot.jpg" style="width:25em;display:block"><img src="OS-could-not-be-updated-reboot.jpg" alt="Adding an account" class="md_thumbnail" style="max-width:100%"/></a>|
```suggestion
|<a href="OS-could-not-be-updated-reboot.jpg" style="width:25em;display:block"><img src="OS-could-not-be-updated-reboot.jpg" alt="OS could not be updated - reboot" class="md_thumbnail" style="max-width:100%"/></a>|
```

2022-10-13 22:04 UTC, sledges commented on Support/Help_Articles/Updating_Sailfish_OS/README.md
> +|<a href="Example-ssu-lr-xa2.png" style="width:50em;display:block"><img src="Example-ssu-lr-xa2.png" alt="Adding an account" class="md_thumbnail" style="max-width:100%"/></a>|
```suggestion
|<a href="Example-ssu-lr-xa2.png" style="width:50em;display:block"><img src="Example-ssu-lr-xa2.png" alt="Example ssu lr" class="md_thumbnail" style="max-width:100%"/></a>|
```

2022-10-13 22:04 UTC, sledges commented on Support/Help_Articles/Updating_Sailfish_OS/README.md
> +|<span class="md_figcaption">OS installation failed</span>|
```suggestion
|<span class="md_figcaption">Output of `ssu lr`</span>|
```

2022-10-14 09:20 UTC, vigejolla commented
Looks good, but please rebase on top of master

2022-10-14 09:47 UTC, vigejolla commented on Support/Help_Articles/Updating_OS/README.md
> +nav_order: 90
I don't really care what the order is, but... In my alphabet U(pdating Sailfish OS) is after T(ips and Tricks). But the nav_order 1000 in "Tips and Tricks" hints that perhaps it is supposed to be after all the other pages, which should be in alphabetical order? Like I said, I don't care about the order, I just want to be sure the end result is what you want.

2022-10-14 09:49 UTC, vigejolla approved these changes
LGTM. Just one question about the order of pages (to make sure). After that I can merge this.

2022-10-14 10:19 UTC, jovirkku commented
> LGTM. Just one question about the order of pages (to make sure). After that I can merge this.

I am not sure if there is a question for me. I have tried to get the docs under Help Articles in alphabetical order (in the lack of any guidance).

2022-10-14 10:36 UTC, vigejolla commented
> I am not sure if there is a question for me. I have tried to get the docs under Help Articles in alphabetical order (in the lack of any guidance).

Yes, there was a question, as I wasn't sure if that was indeed what you wanted. And since the pages are *not* in alphabetical order, I suppose there is something left to fix. e.g. increase nav_order to something above 1000.

2022-10-17 05:00 UTC, merged