Actually install and enable ccache for A10+
sailfishos/docs.sailfishos.org pull request #139
Opened 2022-10-16 21:14 UTC by voidanix

Since Android 10, ccache is no longer shipped as a prebuilt and its path must be
specified through CCACHE_EXEC

See: https://cs.android.com/android/platform/superproject/+/android10-release:build/make/core/ccache.mk;l=31

2022-10-16 21:21 UTC, Thaodan requested changes
Some small changes nitpicks except that it looks good to me.

2022-10-16 21:21 UTC, Thaodan commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_10_Build_and_Flash/README.md
>  export USE_CCACHE=1
Can you move the install ccache to the earlier apt-get install call?
No need to remove the line the var is only used when calling make.

2022-10-16 21:21 UTC, Thaodan commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +sudo apt install ccache
Same here

2022-10-16 21:29 UTC, voidanix commented
Should be OK now

2022-10-16 21:33 UTC, Thaodan approved these changes
LGTM

2022-10-17 20:25 UTC, Thaodan commented
> @voidanix could you please rebase on top of master, I can then merge this

There's also a rebase and merge button.

2022-10-18 04:32 UTC, merged

2022-10-18 04:33 UTC, vigejolla commented
> There's also a rebase and merge button.

My understanding is that it does a different thing, i.e. it just adds the commits from the PR directly on top of master, i.e. there will be no merge commit.