Creating of Shared Device Multiple Users document
sailfishos/docs.sailfishos.org pull request #154
Opened 2022-11-02 13:12 UTC by jpwalden

Signed-off-by: jari-pekka walden <jari-pekka.walden@jolla.com>

2022-11-02 13:45 UTC, jovirkku requested changes

2022-11-02 13:45 UTC, jovirkku commented on Support/Help_Articles/Shared_Device_Multiple_Users/README.md
> +* do not see Android App Support and Android app (not on OS release 3.4.0 at least)
This part is not needed anymore: "(not on OS release 3.4.0 at least)"

2022-11-02 13:45 UTC, jovirkku commented on Support/Help_Articles/Shared_Device_Multiple_Users/README.md
> +The admin has the same rights as the default user of Sailfish, "nemo", has had so far, up to OS release 3.3.0.
_(this is originally my text - it looks outdated now)_  Let's change it  (line 48) to:
The admin equals the default user of Sailfish, so "defaultuser" (it used to be called "nemo" on Sailfish 3).

2022-11-02 13:45 UTC, jovirkku commented on Support/Help_Articles/Shared_Device_Multiple_Users/README.md
> +* Admin has a human-friendly name in "Settings > Users", with the role "Admin" shown underneath the name. The given name can be tens of characters long.
_(again, my bad text)_  Let's go with this (line 50):
Admin can set a human-friendly name in "Settings > System > Users" to replace "defaultuser". His/her role "Admin" will be shown underneath the new name in the same menu. The given name can be tens of characters long.

2022-11-03 07:51 UTC, jpwalden commented on Support/Help_Articles/Shared_Device_Multiple_Users/README.md
> +* do not see Android App Support and Android app (not on OS release 3.4.0 at least)
Thanks, fixed

2022-11-03 07:51 UTC, jpwalden commented on Support/Help_Articles/Shared_Device_Multiple_Users/README.md
> +The admin has the same rights as the default user of Sailfish, "nemo", has had so far, up to OS release 3.3.0.
Thanks, fixed

2022-11-03 07:51 UTC, jpwalden commented on Support/Help_Articles/Shared_Device_Multiple_Users/README.md
> +* Admin has a human-friendly name in "Settings > Users", with the role "Admin" shown underneath the name. The given name can be tens of characters long.
Thanks, fixed

2022-11-03 09:06 UTC, jovirkku approved these changes
This is ok, imho.

2022-11-03 09:54 UTC, vigejolla commented on Support/Help_Articles/Shared_Device_Multiple_Users/README.md
> +nav_order: 500
This places the page before "SD Card Format and Encryption". In my alphabet D is before h.

2022-11-03 12:57 UTC, jpwalden commented on Support/Help_Articles/Shared_Device_Multiple_Users/README.md
> +nav_order: 500
Fixed, that "SD Card Format and Encryption" wasn't there (or I missed it) when I pushed this so therefore I had wrong order, now that should be ok.

2022-11-03 12:58 UTC, vigejolla approved these changes

2022-11-03 12:59 UTC, merged