Creating QR code reader document
sailfishos/docs.sailfishos.org pull request #175
Opened 2022-11-14 14:09 UTC by jpwalden

Signed-off-by: jari-pekka walden <jari-pekka.walden@jolla.com>

2022-11-14 15:59 UTC, jovirkku approved these changes
LGTM.  Nothing to change.

2022-11-15 05:21 UTC, vigejolla commented
Nitpick: Please change the commit message to imperative form: "Create QR code reader document"

2022-11-15 07:06 UTC, vigejolla requested changes

2022-11-15 07:06 UTC, vigejolla commented on Support/Help_Articles/QR_code_Reader/README.md
> +permalink: Support/Help_Articles/QR_Code_Reader/
The title and permalink have capital C, while the directory name has lower case c. I suggest you rename the directory.

2022-11-15 07:49 UTC, jpwalden commented on Support/Help_Articles/QR_code_Reader/README.md
> +permalink: Support/Help_Articles/QR_Code_Reader/
Ok, renamed.

2022-11-15 08:01 UTC, merged