Create Recovery mode document
sailfishos/docs.sailfishos.org pull request #182
Opened 2022-11-18 09:49 UTC by jpwalden

Signed-off-by: jari-pekka walden <jari-pekka.walden@jolla.com>

2022-11-21 11:07 UTC, jovirkku requested changes

2022-11-21 11:07 UTC, jovirkku commented on Support/Help_Articles/Recovery_Mode/README.md
> +When the process has completed, please refer to [chapter 4](https://jolla.zendesk.com/hc/en-us/articles/360021620740#4) to correctly revert your phone from the Recovery Mode back to its normal state.
Use this sentence, instead:

When the process is complete, you will need to revert the phone back to its normal state as instructed in chapter [Reverting phone back to the normal state](https://github.com/sailfishos/docs.sailfishos.org/pull/182/files#reverting-phone-back-to-the-normal-state) of this document.

2022-11-21 11:07 UTC, jovirkku commented on Support/Help_Articles/Recovery_Mode/README.md
> +Please read this general [**article about factory reset**](/Support/Help_Articles/Factory_Reset/). In particular, read what is recommended after the factory reset, as explained in chapter "First acti
I believe we can remove this sentence. The user may not have executed the factory reset at all (but some other fixes).

2022-11-21 11:07 UTC, jovirkku commented on Support/Help_Articles/Recovery_Mode/README.md
> +* Skip to [chapter 4](https://jolla.zendesk.com/hc/en-us/articles/360021620740#4) now.
Replace with:

Skip to chapter [Reverting phone back to the normal state](https://github.com/sailfishos/docs.sailfishos.org/pull/182/files#reverting-phone-back-to-the-normal-state) of this document now.

2022-11-21 11:12 UTC, jovirkku commented on Support/Help_Articles/Recovery_Mode/README.md
> +* Skip to [chapter 4](https://jolla.zendesk.com/hc/en-us/articles/360021620740#4) now.
JP, check all the links pointing to "chapter 4" that I gave. There are relational (local) so now pointing to GitHub. Do not copy them as such!

2022-11-21 13:10 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +* You will need the same version of hybris-recovery.img as belongs to the Sailfish OS version of your phone currently. In other words, if you have updated OS version 4.1.0 (say) to your phone, then y
Thanks, rephrased.

2022-11-21 13:10 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +11. Launch either a) the CMD terminal on the PC or b) the Putty application. So, use either option a) or b) below.
fixed

2022-11-21 13:10 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +You are now ready to move to **Chapter 3**](https://jolla.zendesk.com/hc/en-us/articles/204709607#3) Fixing your device with Recovery Mode.
added/updated

2022-11-21 13:10 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +You are now ready to move to [**Chapter 3**](https://jolla.zendesk.com/hc/en-us/articles/204709607#3) Fixing your device with Recovery Mode.
added/updated

2022-11-21 13:11 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +**It is mandatory** to obtain the same version of hybris-boot.img that belongs to the Sailfish OS version of your phone currently. In other words, if you have updated OS version 4.1.0 (say) to your p
Updated

2022-11-21 13:11 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +Press [Enter] to return to recovery menu... `
yes, removed.

2022-11-21 13:11 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +When the process has completed, please refer to [chapter 4](https://jolla.zendesk.com/hc/en-us/articles/360021620740#4) to correctly revert your phone from the Recovery Mode back to its normal state.
Updated

2022-11-21 13:11 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +Please read this general [**article about factory reset**](/Support/Help_Articles/Factory_Reset/). In particular, read what is recommended after the factory reset, as explained in chapter "First acti
Valid point -removed.

2022-11-21 13:13 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +* Skip to [chapter 4](https://jolla.zendesk.com/hc/en-us/articles/360021620740#4) now.
Thanks for the comment, should be ok.

2022-11-21 13:15 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +8) Then select "Remote NDIS Compatible Device".
Tried to test that part, but couldn't yet verify this part, since my fastboot driver update fails to work.

2022-11-21 13:49 UTC, jovirkku commented on Support/Help_Articles/Recovery_Mode/README.md
> +After you have fixed what you need to fix, do not forget to return to [the chapter Reverting phone back to the normal state](#Reverting-phone-back-to-the-normal-state) of this document. You must reve
Change this:
do not forget to return to [the chapter Reverting phone back to the normal state](#Reverting-phone-back-to-the-normal-state) of this document

.. this:
do not forget to return to the chapter [Reverting phone back to the normal state](#reverting-phone-back-to-the-normal-state) of this document

(so, a lower case R. And I would think "the chapter" does not deserve the link.
The same change to all similar ones.

2022-11-22 05:08 UTC, vigejolla commented on Support/Help_Articles/Recovery_Mode/README.md
> +You are now ready to move to **Chapter 3**](https://jolla.zendesk.com/hc/en-us/articles/204709607#3) Fixing your device with Recovery Mode.
You didn't add the link

2022-11-22 05:10 UTC, vigejolla commented on Support/Help_Articles/Recovery_Mode/README.md
> +You are now ready to move to [**Chapter 3**](https://jolla.zendesk.com/hc/en-us/articles/204709607#3) Fixing your device with Recovery Mode.
Also this link points to old document, should be `#fixing-your-device-with-the-recovery-mode` instead

2022-11-22 05:12 UTC, vigejolla commented on Support/Help_Articles/Recovery_Mode/README.md
> +When the process has completed, please refer to [chapter 4](https://jolla.zendesk.com/hc/en-us/articles/360021620740#4) to correctly revert your phone from the Recovery Mode back to its normal state.
Again, you just added the text without the link

2022-11-22 05:14 UTC, vigejolla commented on Support/Help_Articles/Recovery_Mode/README.md
> +* Skip to [chapter 4](https://jolla.zendesk.com/hc/en-us/articles/360021620740#4) now.
No they aren't. Try searching for "chapter 4". The very first match is a link to old document.

2022-11-22 05:17 UTC, vigejolla commented on Support/Help_Articles/Recovery_Mode/README.md
> +After you have fixed what you need to fix, do not forget to return to [the chapter Reverting phone back to the normal state](#Reverting-phone-back-to-the-normal-state) of this document. You must reve
I'm quite sure jovirkku meant only that the "the chapter" should be left outside of the link, i.e. have `the chapter [Reverting phone back to normal state](#reverting-phone-back-to-the-normal-state)`

2022-11-22 08:13 UTC, jovirkku commented on Support/Help_Articles/Recovery_Mode/README.md
> +After you have fixed what you need to fix, do not forget to return to [the chapter Reverting phone back to the normal state](#Reverting-phone-back-to-the-normal-state) of this document. You must reve
Yes, it was what I meant. Take just "the chapter" outside of the link.

2022-11-22 12:05 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +You are now ready to move to **Chapter 3**](https://jolla.zendesk.com/hc/en-us/articles/204709607#3) Fixing your device with Recovery Mode.
Thanks, now added

2022-11-22 12:06 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +* Skip to [chapter 4](https://jolla.zendesk.com/hc/en-us/articles/360021620740#4) now.
Thanks, fixed.

2022-11-22 12:07 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +After you have fixed what you need to fix, do not forget to return to [the chapter Reverting phone back to the normal state](#Reverting-phone-back-to-the-normal-state) of this document. You must reve
ok, my bad, fixed.

2022-11-22 12:07 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +You are now ready to move to [**Chapter 3**](https://jolla.zendesk.com/hc/en-us/articles/204709607#3) Fixing your device with Recovery Mode.
yes it should, fixed.

2022-11-22 12:07 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +You are now ready to move to [**Chapter 3**](https://jolla.zendesk.com/hc/en-us/articles/204709607#3) Fixing your device with Recovery Mode.
yes, fixed.

2022-11-22 12:18 UTC, vigejolla commented on Support/Help_Articles/Recovery_Mode/README.md
> +If this worked correctly you would see the black Recovery Mode menu on your computer screen (below). You are now ready to move to [chapter](#fixing-your-device-with-the-recovery-mode) Fixing your dev
Now these look a bit silly, when the word "chapter" is the link. Perhaps it would look better like `You are now ready to move to chapter [Fixing your device with Recovery Mode](#fixing-your-device-with-the-recovery-mode)` ?

2022-11-22 12:51 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +If this worked correctly you would see the black Recovery Mode menu on your computer screen (below). You are now ready to move to [chapter](#fixing-your-device-with-the-recovery-mode) Fixing your dev
Valid point, it is better that way - fixed.

2022-11-23 05:31 UTC, vigejolla commented on Support/Help_Articles/Recovery_Mode/README.md
> +4) Once the driver is installed, attach your Xperia 10 II to your Mac. (Note: Jolla must be in "Recovery Mode" before attaching the cable, see this [chapter](#forcing-xperia-10-ii-or-xperia-10-iii-to
```suggestion
4) Once the driver is installed, attach your Xperia 10 II to your Mac. (Note: The phone must be in "Recovery Mode" before attaching the cable, see this [chapter](#forcing-xperia-10-ii-or-xperia-10-iii-to-the-recovery-mode))
```

2022-11-23 06:06 UTC, jpwalden commented on Support/Help_Articles/Recovery_Mode/README.md
> +4) Once the driver is installed, attach your Xperia 10 II to your Mac. (Note: Jolla must be in "Recovery Mode" before attaching the cable, see this [chapter](#forcing-xperia-10-ii-or-xperia-10-iii-to
Thanks, nicely spotted -fixed now.

2022-11-23 06:38 UTC, vigejolla approved these changes

2022-11-23 06:38 UTC, merged