SSH and SCP
sailfishos/docs.sailfishos.org pull request #191
Opened 2022-11-28 12:32 UTC by jovirkku

Signed-off-by: Jorma Virkkunen <jorma.virkkunen@jolla.com>

2022-11-28 12:34 UTC, jovirkku commented
Help_Articles:
    SSH_and_SCP:
        SSH_and_SCP_Linux
        SSH_and_SCP_Mac
        SSH_and_SCP_Windows

2022-11-28 13:00 UTC, jpwalden approved these changes
Looks good to me and good idea to structure these documents this way.

2022-11-28 13:32 UTC, vigejolla requested changes
I like the idea, but some fixes are needed. Also, I think we should consider combining some of the already existing pages under a common page, e.g. All "Setup * Account" pages could be under a single "Account Setup" page. That's outside of the scope of this task, but just saying :)

2022-11-28 13:32 UTC, vigejolla commented on Support/Help_Articles/SSH_and_SCP/README.md
> +permalink: Support/Help_Articles/SSH_and_SCP/
missing parent

2022-11-28 13:32 UTC, vigejolla commented on Support/Help_Articles/SSH_and_SCP/SSH_and_SCP_Linux/README.md
> +parent: SSH_and_SCP
parent should be the title and not directory name, i.e. `SSH and SCP`

2022-11-28 13:32 UTC, vigejolla commented on Support/Help_Articles/SSH_and_SCP/SSH_and_SCP_Linux/README.md
> +parent: SSH_and_SCP
Also needs `grand_parent: Help Articles`

2022-11-28 13:32 UTC, vigejolla commented on Support/Help_Articles/SSH_and_SCP/SSH_and_SCP_Linux/README.md
> +parent: SSH_and_SCP
The above comments apply to all three child documents

2022-11-28 15:42 UTC, jovirkku commented on Support/Help_Articles/SSH_and_SCP/SSH_and_SCP_Linux/README.md
> +parent: SSH_and_SCP
Parents and Grandparents fixed.

2022-11-28 15:43 UTC, jovirkku commented on Support/Help_Articles/SSH_and_SCP/README.md
> +permalink: Support/Help_Articles/SSH_and_SCP/
Added

2022-11-28 15:44 UTC, jovirkku commented
I believe this is ready now.

2022-11-28 16:54 UTC, jovirkku commented
A hyperlink at the end of the Mac document was still fixed, thanks to PR #192.

2022-11-29 05:37 UTC, vigejolla approved these changes
LGTM, but if you don't mind I'll merge this together with PR #192.

2022-11-29 07:41 UTC, merged