Collecting basic logs
sailfishos/docs.sailfishos.org pull request #203
Opened 2022-12-08 13:39 UTC by jovirkku

Signed-off-by: Jorma Virkkunen <jorma.virkkunen@jolla.com>

2022-12-08 13:55 UTC, jovirkku commented
If our goal here is to move this document from ZD to SailfishOS Docs and check the text of the document then this PR should be ok.
However, if we also want to review the actual script then a different approach is needed as GitHub does not reveal the contents of the zipped script.

2022-12-09 22:52 UTC, Thaodan commented
> If our goal here is to move this document from ZD to SailfishOS Docs and check the text of the document then this PR should be ok. However, if we also want to review the actual script then a different approach is needed as GitHub does not reveal the contents of the zipped script.

The script could go to a separate repo, for each version tagged there will be a tarball to download that would make the process more transparent and contributions to the script get easier.

2022-12-12 11:43 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_Basic_Logs/README.md
> +**[collect-logs.sh](/Support/Help_Articles/Collecting_Logs/Collecting_Basic_Logs/collect-logs.sh)**
Path is wrong here, it should be "Collect_Basic_Logs". On the other hand, you could probably leave the entire path out, and just have `[collect-logs.sh](collect-logs.sh)` here. Didn't try though.

2022-12-12 11:43 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_Basic_Logs/collect-logs.sh
> +
Quite a lot of empty rows here, perhaps they could be cleaned out?

2022-12-12 11:44 UTC, jovirkku commented on Support/Help_Articles/Collecting_Logs/Collect_Basic_Logs/README.md
> +**[collect-logs.sh](/Support/Help_Articles/Collecting_Logs/Collecting_Basic_Logs/collect-logs.sh)**
A good catch, thanks

2022-12-12 11:44 UTC, vigejolla requested changes
Please fix the link

2022-12-12 11:46 UTC, jovirkku commented on Support/Help_Articles/Collecting_Logs/Collect_Basic_Logs/collect-logs.sh
> +
They are there intentionally, to give rhythm to the output == make it easier to read. Like I commented, I removed many of them already  :-)

2022-12-12 12:05 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_Basic_Logs/collect-logs.sh
> +
Tried it, works well, collected lot's of valuable information.

2022-12-12 12:06 UTC, vigejolla approved these changes

2022-12-12 12:06 UTC, merged