Document how to get backtrace with gdb at boot from any service
sailfishos/docs.sailfishos.org pull request #211
Opened 2022-12-14 14:22 UTC by LaakkonenJussi

Added documentation about how to get backtrace from services that crash at boot. This requires only gdb and the relevant debuginfo packages to be installed and shows straightforward way for service debug with gdb.

2022-12-15 05:30 UTC, vigejolla approved these changes
LGTM

2022-12-15 05:53 UTC, Thaodan reviewed
All in all looks good to me, only some smaller suggestions.
I'm wondering is there a bug for this?

2022-12-15 05:53 UTC, Thaodan commented on Reference/Sailfish_OS_Cheat_Sheet/README.md
> +And add a systemd drop-in file to `/usr/lib/systemd/system/<service_name>.service.d/override.conf` with the content to override the existing service file variables:
If using devel-su -c 'systemctl edit <service>' you can avoid the manual steps to create the directory, the files and system daemon reload.

2022-12-15 05:53 UTC, Thaodan commented on Reference/Sailfish_OS_Cheat_Sheet/README.md
> +```
You can use `pkcon refresh && pkcon install gdb` for easier refresh.

2022-12-15 08:49 UTC, LaakkonenJussi commented on Reference/Sailfish_OS_Cheat_Sheet/README.md
> +And add a systemd drop-in file to `/usr/lib/systemd/system/<service_name>.service.d/override.conf` with the content to override the existing service file variables:
I need to try this. I was not aware of that, I usually do the things the hard way.

2022-12-15 08:50 UTC, LaakkonenJussi commented on Reference/Sailfish_OS_Cheat_Sheet/README.md
> +```
I'd rather use `zypper ref tools` but I guess `pkcon` is preferred usually as it is installed already on the devices.

2022-12-15 09:03 UTC, vigejolla requested changes

2022-12-15 09:03 UTC, vigejolla commented on Reference/Sailfish_OS_Cheat_Sheet/README.md
> +```ssu ar tools
I just now noticed that you had the first line of commands on the same line as backticks. This does not work, they need to be on separate lines. The same error is on all instances where you added code blocks.

And then I noticed that you used the tools repo, which I believe doesn't work on release devices. I think gdb is found on sdk repo there. I don't have any release device at hand so I can't easily verify though.

2022-12-15 09:21 UTC, LaakkonenJussi commented on Reference/Sailfish_OS_Cheat_Sheet/README.md
> +And add a systemd drop-in file to `/usr/lib/systemd/system/<service_name>.service.d/override.conf` with the content to override the existing service file variables:
Actually, `systemctl edit` creates the overrides to `/etc/systemd/system/` and then the changes made to the location we use by default (`/usr/lib/systemd/system/`) do not work afterwards for the service. Apparently one would have to manually remove the `/etc/systemd/system/<servicename>.service.d/*.conf`. I think manual steps here are more obvious. Usually systemd tools just obfuscate things (I do not trust them).

2022-12-15 09:29 UTC, LaakkonenJussi commented on Reference/Sailfish_OS_Cheat_Sheet/README.md
> +```
Changed to oneliner.

2022-12-15 09:32 UTC, LaakkonenJussi commented on Reference/Sailfish_OS_Cheat_Sheet/README.md
> +And add a systemd drop-in file to `/usr/lib/systemd/system/<service_name>.service.d/override.conf` with the content to override the existing service file variables:
Also, when and if we change the location where `systemctl edit` makes the changes we'd have then outdated location here in the docs. By telling the exact location here and forcing to do a bit of manual labor the details are always permanent. This isn't really something one needs to do even on monthly, let alone weekly basis.

2022-12-15 09:33 UTC, LaakkonenJussi commented on Reference/Sailfish_OS_Cheat_Sheet/README.md
> +```ssu ar tools
Right, I guess the format details were not correct. Made the changes to format.

And changed to use the sdk repo. Although on devel devices it does not seem to have `gdb`..

2022-12-15 09:56 UTC, LaakkonenJussi commented on Reference/Sailfish_OS_Cheat_Sheet/README.md
> +```ssu ar tools
Oh, no, apparently `gdb` is in sdk repo. Nevermind that.

2022-12-15 10:23 UTC, LaakkonenJussi commented
> LGTM, but please squash the commits

Will do, always :).

2022-12-15 11:38 UTC, Thaodan commented on Reference/Sailfish_OS_Cheat_Sheet/README.md
> +And add a systemd drop-in file to `/usr/lib/systemd/system/<service_name>.service.d/override.conf` with the content to override the existing service file variables:
> Actually, `systemctl edit` creates the overrides to `/etc/systemd/system/` and then the changes made to the location we use by default (`/usr/lib/systemd/system/`) do not work afterwards for the service. Apparently one would have to manually remove the `/etc/systemd/system/<servicename>.service.d/*.conf`. I think manual steps here are more obvious. Usually systemd tools just obfuscate things (I do not trust them).

the changes can be revert with systemctl revert.

2022-12-15 14:27 UTC, LaakkonenJussi commented on Reference/Sailfish_OS_Cheat_Sheet/README.md
> +And add a systemd drop-in file to `/usr/lib/systemd/system/<service_name>.service.d/override.conf` with the content to override the existing service file variables:
We could separately raise this issue in the documentation with the warning that `revert` will cancel all changes and the changes are stored elsewhere than what we commonly use as location when `edit` is used. Perhaps a reference later on then to that section somewhere in this added documentation is in place. Therefore, resolving this.

2022-12-16 15:04 UTC, merged

2022-12-16 21:08 UTC, Thaodan commented on Reference/Sailfish_OS_Cheat_Sheet/README.md
> +And add a systemd drop-in file to `/usr/lib/systemd/system/<service_name>.service.d/override.conf` with the content to override the existing service file variables:
> We could separately raise this issue in the documentation with the warning that `revert` will cancel all changes and the changes are stored elsewhere than what we commonly use as location when `edit` is used. Perhaps a reference later on then to that section somewhere in this added documentation is in place. Therefore, resolving this.

I wasn't aware of that, will check.