Publishing Sailfish OS updates
sailfishos/docs.sailfishos.org pull request #241
Opened 2023-01-19 08:41 UTC by jovirkku

Signed-off-by: Jorma Virkkunen <jorma.virkkunen@jolla.com>

2023-01-19 09:08 UTC, jpwalden requested changes
"We have a small number of technically oriented people, "geeks", who have signed a Non-Disclosure Agreement (NDA) with Jolla."
I would edit this a bit since, I wouldn't want to call cbeta people as "geeks" since some of them might not like that.  I think the "technically oriented people" is good, so I would remove the geeks.
Then a comment, I'm not sure how actively we are to get more people on the cbeta group (I would assume we are, at least I am :) ), but would be good to have here some information how you can apply to the cbeta group if you are interested. This is just a comment since I'm not aware how actively we are looking more people and I'm also not sure how the process even works.

2023-01-19 11:06 UTC, jovirkku commented
Everything about cbeta and community testing was removed.
Added the link to the table of official releases.

2023-01-19 11:20 UTC, jpwalden approved these changes
Looks good to me

2023-01-20 05:23 UTC, vigejolla commented on Support/Help_Articles/Publishing_Sailfish_OS_Updates/README.md
> +nav_order: 625
Now this page is after "QR Code Reader", shouldn't it be before?

2023-01-23 08:08 UTC, jovirkku commented on Support/Help_Articles/Publishing_Sailfish_OS_Updates/README.md
> +nav_order: 625
Yes, definitely.
Fixed.

2023-01-23 08:13 UTC, vigejolla approved these changes

2023-01-23 08:14 UTC, merged