Add Firewall description from ZenDesk
sailfishos/docs.sailfishos.org pull request #255
Opened 2023-02-03 14:58 UTC by LaakkonenJussi

Moved https://jolla.zendesk.com/hc/en-us/articles/360017800813-Firewall-in-Sailfish-OS to forum format. Also updated any outdated or wrong info on the page.

2023-02-06 08:01 UTC, vigejolla commented on Support/Help_Articles/Firewall/README.md
> +     5.1 a temporary solution to allow all traffic by default on IPv4:
Markdown doesn't really support having "five point something" in numbered lists. My suggestion: Use a bullet list as a second list, so something like:
```
  5. If the problem is with dropping packets, you can try either:
   * a temporary solution to allow all traffic by default on IPv4:
     or
   * if you wish it to be permanent, add file **/etc/connman/firewall.d/99-accept-all-firewall.conf** and write the following lines to it:
```

2023-02-06 08:02 UTC, vigejolla commented on Support/Help_Articles/Firewall/README.md
> +If the device for some reason does not boot, enter the recovery mode and setup the same content for the configuration file as in section 5.2. If the device boots after this please report this problem
That "section 5.2" should probably be a link to somewhere

2023-02-06 08:03 UTC, vigejolla commented on Support/Help_Articles/Firewall/README.md
> +      2: `firewall.d/10-firewall.conf` - has `[wifi]` rules
These numbers 2-4 should also have '.' after the number instead of ':'

2023-02-06 08:03 UTC, vigejolla requested changes
I'm sure the content itself is fine, but those lists need a little bit of finetuning

2023-02-06 15:57 UTC, LaakkonenJussi commented on Support/Help_Articles/Firewall/README.md
> +If the device for some reason does not boot, enter the recovery mode and setup the same content for the configuration file as in section 5.2. If the device boots after this please report this problem
Yeah, I did a reformat on this part. Thanks for pointing it out. I hope it is now clearer even. No need to mention boot issues I guess, since that has not been the case for years.

2023-02-06 15:58 UTC, LaakkonenJussi commented on Support/Help_Articles/Firewall/README.md
> +      2: `firewall.d/10-firewall.conf` - has `[wifi]` rules
Yeap, missed that. Thanks.

2023-02-07 05:24 UTC, vigejolla requested changes

2023-02-07 05:24 UTC, vigejolla commented on Support/Help_Articles/Firewall/README.md
> +  6. If the problem was solved with this, please report this problem at [SailfishOS forum](forum.sailfishos.org).
```suggestion
  6. If the problem was solved with this, please report this problem at [Sailfish OS Forum](https://forum.sailfishos.org).
```

2023-02-07 05:24 UTC, vigejolla commented on Support/Help_Articles/Firewall/README.md
> +If there are other network related issues with the device try the example configuration above (**99-accept-all-firewall.conf**) to solve the issue if it seems like a firewall issue. If this solves an
```suggestion
If there are other network related issues with the device try the example configuration above (**99-accept-all-firewall.conf**) to solve the issue if it seems like a firewall issue. If this solves any issue please report the problem with logs at [Sailfish OS Forum](https://forum.sailfishos.org).
```

2023-02-09 05:45 UTC, vigejolla approved these changes
LGTM, one nitpick still though: There should be a space between "Sailfish" and "OS" in "Sailfish OS Forum"

2023-02-09 07:37 UTC, jpwalden approved these changes
Looks good to me

2023-02-09 08:27 UTC, LaakkonenJussi commented
> LGTM, one nitpick still though: There should be a space between "Sailfish" and "OS" in "Sailfish OS Forum"

Ah yeah, minor issue but `sed`able ;). Done.

2023-02-09 11:12 UTC, merged