Create Messages Troubleshooting document
sailfishos/docs.sailfishos.org pull request #259
Opened 2023-02-10 09:46 UTC by jpwalden

Signed-off-by: jari-pekka walden <jari-pekka.walden@jolla.com>

2023-02-14 08:27 UTC, jovirkku requested changes

2023-02-14 08:27 UTC, jovirkku commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +[³] August 2021:  Not yet available for Xperia 10 II (it requires apps in the 64-bit architecture)
In fact, also the 64-bit versions are available at https://openrepos.net/content/slava/mms-logger. 
If we do not want to rely on O.R, then update "August 2021".

2023-02-14 08:27 UTC, jovirkku commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +* If you can either send but not receive MMS messages, or vice versa, usually your settings are correct. Please check with your operator that no blocks are in place. Also, make sure you aren't roamin
I would drop the word "either" from the sentence.

2023-02-14 08:27 UTC, jovirkku commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +2. Launch MMS Logger. Pull down Settings. Select > Ofono log > Full.
Remove "Select > Ofono log > Full."  There is nothing like that in the pulley of this app. Especially not "oFono".

2023-02-14 08:27 UTC, jovirkku commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +* **Check the network settings** at "Settings > System > Mobile network > MMS access point" (see the picture below). Ensure that they match with the information available at the Internet service of y
The sentence "We recommend using IPv4 (shown as "IP" in the options list) as there are some known issues with IPv6." was probably written by me some years back. Now, I found it a bit odd as the IP version is dictated by the operator.
I would drop the sentence completely.

2023-02-14 13:16 UTC, jpwalden commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +* If you can either send but not receive MMS messages, or vice versa, usually your settings are correct. Please check with your operator that no blocks are in place. Also, make sure you aren't roamin
Yes, good catch, removed

2023-02-14 13:16 UTC, jpwalden commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +2. Launch MMS Logger. Pull down Settings. Select > Ofono log > Full.
Thanks, removed that

2023-02-14 13:16 UTC, jpwalden commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +* **Check the network settings** at "Settings > System > Mobile network > MMS access point" (see the picture below). Ensure that they match with the information available at the Internet service of y
Yes, that is obsolete, removed.

2023-02-15 05:39 UTC, vigejolla requested changes
A couple of issues to fix

2023-02-15 05:39 UTC, vigejolla commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +Jolla Store has an application called MMS Logger. 64-bit architecture version can be found from [Openrepos](#https://openrepos.net/content/slava/mms-logger/). It makes it easier to collect MMS logs f
```suggestion
Jolla Store has an application called MMS Logger. 64-bit architecture version can be found from [Openrepos](https://openrepos.net/content/slava/mms-logger/). It makes it easier to collect MMS logs from the phone. It is to be used in this way:
```

2023-02-15 05:39 UTC, vigejolla commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +2. Launch MMS Logger. Pull down Settings. Select > Ofono log > Full.
There's still "Pull down Settings". I didn't check what's actually there, but to me it sounds weird that we should open settings if we don't make any changes there.

2023-02-15 05:39 UTC, vigejolla commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +* **Check the app settings** at "Settings > Apps > Messages > MMS".  Compare "Maximum message size" to the size of the picture you are trying to send. In case of reception problems, see that you have
Please use proper MarkDown footnotes `[^1] ` instead of `[¹]` here. Check that your editor doesn't change `^1` to `¹`. Some editors try to be a bit too helpful sometimes...

2023-02-15 05:39 UTC, vigejolla commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +* **Check the network settings** at "Settings > System > Mobile network > MMS access point" (see the picture below). Ensure that they match with the information available at the Internet service of y
Same footnote thing here

2023-02-15 05:39 UTC, vigejolla commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +[¹] & [²]:  NOTE concerning dual-SIM phones. Both of the mentioned menu pages contain support for two SIM cards. However, only one SIM card can be active for outgoing messages (and phone calls) at a
And finally here you should have: `[^1]: `. I doubt MarkDown allows combining footnotes like that, so you shoud probably only have `[^1]` and use it in both occasions above.

2023-02-15 08:53 UTC, jpwalden commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +2. Launch MMS Logger. Pull down Settings. Select > Ofono log > Full.
Yes, that is not needed -> removed

2023-02-15 08:54 UTC, jpwalden commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +Jolla Store has an application called MMS Logger. 64-bit architecture version can be found from [Openrepos](#https://openrepos.net/content/slava/mms-logger/). It makes it easier to collect MMS logs f
Thanks, fixed

2023-02-15 08:55 UTC, jpwalden commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +* **Check the app settings** at "Settings > Apps > Messages > MMS".  Compare "Maximum message size" to the size of the picture you are trying to send. In case of reception problems, see that you have
Good catch, for some reason it was changed by gedit, needed to remove and add it again -> fixed

2023-02-15 08:55 UTC, jpwalden commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +* **Check the network settings** at "Settings > System > Mobile network > MMS access point" (see the picture below). Ensure that they match with the information available at the Internet service of y
fixed

2023-02-15 08:56 UTC, jpwalden commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +[¹] & [²]:  NOTE concerning dual-SIM phones. Both of the mentioned menu pages contain support for two SIM cards. However, only one SIM card can be active for outgoing messages (and phone calls) at a
yes, that wasn't needed anymore, so removed the 2nd footnote

2023-02-15 09:01 UTC, vigejolla commented on Support/Help_Articles/Messages_Troubleshooting/README.md
> +[^1] :  NOTE concerning dual-SIM phones. Both of the mentioned menu pages contain support for two SIM cards. However, only one SIM card can be active for outgoing messages (and phone calls) at a time
Still not correct.
```suggestion
[^1]:  NOTE concerning dual-SIM phones. Both of the mentioned menu pages contain support for two SIM cards. However, only one SIM card can be active for outgoing messages (and phone calls) at a time, as selected in the menu "Settings > System > SIM cards > Call and messages".  Incoming messages (and calls) work to both SIM cards.
```

2023-02-15 13:04 UTC, merged