Replace ZD links with Docs links where possible
sailfishos/docs.sailfishos.org pull request #262
Opened 2023-02-14 10:11 UTC by jovirkku

Signed-off-by: Jorma Virkkunen <jorma.virkkunen@jolla.com>

2023-02-14 10:14 UTC, jovirkku commented
Raine kindly listed the Docs documents still having Zendesk links in them. I have replaced the majority of those links but not all.
One of the remaining ZD links is the one for filing a new ticket: https://jolla.zendesk.com/hc/en-us/requests/new 

One can run Raine's command again when the time comes.

2023-02-14 13:56 UTC, rainemak commented on Support/Help_Articles/Collecting_Logs/Collect_Email_Logs/README.md
> +The following command colelcts the journal log and prints it out to the file "journal.txt".
```suggestion
The following command collects the journal log and prints it out to the file "journal.txt".
```

2023-02-14 13:59 UTC, rainemak commented on Support/Help_Articles/Factory_Reset/README.md
> +Our instructions for flashing are **[in this support article](https://docs.sailfishos.org/Support/Help_Articles/Reinstalling_Sailfish_OS/)**.
This could be a relative link as far as I can see.

2023-02-15 12:07 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_oFono_Logs/README.md
> -   ```
Why are we removing the instructions for installing the logger from our repos?

2023-02-15 12:15 UTC, vigejolla commented on Support/Help_Articles/Factory_Reset/README.md
> +This is easier and saves you from many extra steps. While the reset reverts your phone to one of the earlier OS versions, you will get the latest OS release
Same comment about unnecessary line breaks here. It's not easy to see what was really changed as github doesn't highlight the changes because of the added line breaks.

2023-02-15 12:39 UTC, vigejolla requested changes
Please remove those extra line breaks

2023-02-15 12:39 UTC, vigejolla commented on Support/Help_Articles/Moving_Files_Between_PC_and_Sailfish_Device/README.md
> +e.g. [**here**](https://askubuntu.com/questions/146529/how-to-connect-mtp-devices-via-usb).
Again those extra linebreaks...

2023-02-15 12:39 UTC, vigejolla commented on Support/Help_Articles/Storage_Space/README.md
> +and for [**Mac users**](/Support/Help_Articles/Moving_Files_between_Mac_and_Sailfish_Device/).
extra line break here as well...

2023-02-15 12:39 UTC, vigejolla commented on Support/Help_Articles/Tips_and_Tricks/README.md
> +**[Jolla Phone](https://jolla.zendesk.com/hc/en-us/articles/204709607)**, and **[Jolla Tablet](https://jolla.zendesk.com/hc/en-us/articles/208406917)**
Again extra line break. To me repeating the Recovery Mode link doesn't make any sense. I'd just have `see the instructions for **[Xperia phones](/Support/Help_Articles/Recovery_Mode)**` Having two links would make sense if they didn't point to the same article...

2023-02-15 12:39 UTC, vigejolla commented on Support/Help_Articles/Tips_and_Tricks/README.md
> +by the name **Utilities** (i.e., there is no app icon at the app grid for it).
again extra line break

2023-02-15 12:39 UTC, vigejolla commented on Support/Help_Articles/Updating_Sailfish_OS/README.md
> +read **[this article](/Support/Help_Articles/Accounts_Setup/Setup_Jolla_Account/)**.
line break...

2023-02-16 11:10 UTC, jovirkku commented on Support/Help_Articles/Collecting_Logs/Collect_oFono_Logs/README.md
> -   ```
It is probably easier without using the command line.

2023-02-16 11:15 UTC, jovirkku commented on Support/Help_Articles/Factory_Reset/README.md
> +This is easier and saves you from many extra steps. While the reset reverts your phone to one of the earlier OS versions, you will get the latest OS release
Sorry. The default text editor of Ubuntu makes very long lines. If there is an URL (to be replaced) beyond the right edge it is darn difficult to edit the URL as the cursor jumps off suddenly. Having all lines completely visible solved the problem.

The "View changes" button top right helps to see the changes. It can present a nice comparison.

2023-02-16 11:33 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_oFono_Logs/README.md
> -   ```
Maybe so, but the whole point of adding it to our repos was to make sure we don't depend on a third party package (yes, slava counts as a third party). I think you can add link to slava's package, but as this is the only place where we document how to install the package from our repos, I really would not like to see the instructions disappear completely. Otherwise soon no one will even remember that we have the package.

2023-02-16 11:35 UTC, vigejolla commented on Support/Help_Articles/Factory_Reset/README.md
> +This is easier and saves you from many extra steps. While the reset reverts your phone to one of the earlier OS versions, you will get the latest OS release
> The "View changes" button top right helps to see the changes. It can present a nice comparison.

No, it does not. That's the whole point. If you didn't add the line breaks it would present a nice comparison, highlighting the actual words which were added/deleted/modified. Now it just shows that the original line was removed and some lines were added instead.

2023-02-16 11:37 UTC, vigejolla commented on Support/Help_Articles/Factory_Reset/README.md
> +This is easier and saves you from many extra steps. While the reset reverts your phone to one of the earlier OS versions, you will get the latest OS release
> Sorry. The default text editor of Ubuntu makes very long lines. If there is an URL (to be replaced) beyond the right edge it is darn difficult to edit the URL as the cursor jumps off suddenly. Having all lines completely visible solved the problem.

Tip 1: Get a decent editor, I recommend emacs
If that's not feasible, tip 2:
Just remove the extra line breaks after you have edited the text?

2023-02-16 13:00 UTC, jovirkku commented
In the latest commit https://github.com/sailfishos/docs.sailfishos.org/commit/774234333bb0c9d938e6ba11789e69cec7185b3c,
I have tried to:
1) Remove the extra line feeds from 5 documents
2) Revert the command line part for installing the oFono Logger to one document.

2023-02-16 13:21 UTC, jovirkku commented
Yet another round was needed: commit https://github.com/sailfishos/docs.sailfishos.org/commit/1dc6e9198199e953deafcf3ee14101a8957f2a5d should fix the rest.

2023-02-17 06:47 UTC, vigejolla commented on Support/Help_Articles/Encryption_of_User_Data/README.md
> +The acceptance of the Security code unlocks the data for use. The unencrypted data is then available for the apps as long as the device is up and running.
Much better now, thank you!

2023-02-17 06:53 UTC, vigejolla approved these changes
LGTM, but I still have one more request: Could you once more rebase on top master?

2023-02-17 07:42 UTC, jovirkku commented
Now?

2023-02-27 10:32 UTC, merged