Upgrade to Stylelint 15 (#1185)
sailfishos/docs.sailfishos.org pull request #286
Opened 2023-03-09 13:06 UTC by vigejolla

At the moment we have disabled stylelint, so this shouldn't really affect anything. But we could get rid of those annoying dependabot alarms.

2023-03-09 13:23 UTC, vigejolla commented
Now this is annoying, I clearly committed and pushed a version of package-lock.json with conflicts. I suspect I forgot to save the file before "git add"...

2023-03-13 08:11 UTC, sledges requested changes
Thank you for bringing things closer to upstream, hopefully the trend persists:)

Minor typo in the commit:
`Ignore ust-the-docs-sfos.scss in style tests` ->
`Ignore just-the-docs-sfos.scss in style tests`

Also the PR is named with upstream's #number, which is not clickable.

Gave couple of comments (rather than requests) inline code.

2023-03-13 08:11 UTC, sledges commented on package.json
> +    "stylelint-check": "stylelint-config-prettier-check"
Why are we reinstating this option? Sorry I haven't (or I don't know how to) setup GitHub's lint checks in my fork of these docs, thus unsure which changes/reverts are actually needed here.

2023-03-13 08:23 UTC, vigejolla commented on package.json
> +    "lint:css": "stylelint '{_sass,assets}/**/*.scss'",
At least I have plenty of .scss files under vendor/bundle/ruby. And they don't pass the inspection. Those probably don't exist when stylelint is run on the CI, but during implementation at least I like to run this on my own laptop. So it makes the life easier when these extra files are ignored. And, now that I have written that sentence, I realize that it would make more sense to add them to `ignoreFiles`, so I will do that.

2023-03-13 08:27 UTC, vigejolla commented on package.json
> +    "lint:formatting": "prettier --check '{_sass,assets}/**/*.{scss,js,json}'",
Yes it does blow up, the same vendor/bundle/ruby files break it. And similarly as with stylelint, that could be added to `.prettierignore`. Which I'll do.

2023-03-13 08:34 UTC, vigejolla commented on package.json
> +    "stylelint-check": "stylelint-config-prettier-check"
No reason at all. I'll remove it.

2023-03-14 07:04 UTC, sledges approved these changes

2023-03-14 07:13 UTC, merged