Update the document. Add the use of Emma
sailfishos/docs.sailfishos.org pull request #287
Opened 2023-03-09 14:15 UTC by jovirkku

2023-03-10 09:17 UTC, vigejolla commented
The PR title could be a bit more specific. i.e. Which document are we updating?

2023-03-10 09:18 UTC, vigejolla commented
> The PR title could be a bit more specific. i.e. Which document are we updating?

Actually, now that I think about it, the whole "Update the document" is kind of pointless. Almost all PRs in this repo update some document. I suggest "Add the use of Emma to Reinstalling Sailfish OS document"

2023-03-10 09:44 UTC, vigejolla requested changes
Some suggestions

2023-03-10 09:44 UTC, vigejolla commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +2.  Use your device and your SIM card with Android OS, checking the main functionality (see chapter [4 Checking that the phone works with Android](#checking-that-the-phone-works-with-android))
I'd drop the chapter number from the link. If the numbering changes in the future, there would be one less thing to fix.

2023-03-10 09:44 UTC, vigejolla commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +4. Run the Emma tool. A view similar to that in Picture 3a should appear. It shows the phone model on the left.
It would be easier to follow if "Picture 3a" was a link to the picture. Just add `name="picture_3a"` to the anchor tag there, and change this one to a link.

2023-03-10 09:44 UTC, vigejolla commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +4. Run the Emma tool. A view similar to that in Picture 3a should appear. It shows the phone model on the left.
```suggestion
4. Run the Emma tool. A view similar to that in [Picture 3a](#picture_3a) should appear. It shows the phone model on the left. 
```

2023-03-10 09:44 UTC, vigejolla commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +* <a href="Emma_X10II_home.png"><img src="Emma_X10II_home.png" alt="Emma home view"></a>
```suggestion
* <a href="Emma_X10II_home.png" name="picture_3a"><img src="Emma_X10II_home.png" alt="Emma home view"></a>
```
Make this image "linkable"

2023-03-10 09:44 UTC, vigejolla commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +    Picture 3a: Initial view of Emma. Xperia 10 II connected.
Now somehow I find it a bit weird to start numbering from "3a". I would have started from 1 ;)

2023-03-10 09:44 UTC, vigejolla commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +As of March 2023, the latest services were as below but note that the exact version ID's can vary by model (regular/Plus/Ultra) and by sales area. The first part of the ID (in bold letters) is signif
```suggestion
As of March 2023, the latest services were as below but note that the exact version ID's can vary by model (regular/Plus/Ultra) and by sales area. The first part of the ID (in bold letters) is significant and should be followed (anything after the letter A may vary and does not matter in this context). This table contains the baseband versions that Jolla has used when testing the Sailfish port. If you selected a more recent version then you take a risk that not everything works as expected.
```

2023-03-10 09:44 UTC, vigejolla commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +_[1] This Android 9 version appears to sometimes get an invalid WiFi MAC which prevents the phone from using WiFi networks (in the Android mode). In such a case, first flash an Android 8 version, boo
How about proper MD footnotes? Or at the very least, add linebreaks.

2023-03-13 07:45 UTC, jovirkku commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +2.  Use your device and your SIM card with Android OS, checking the main functionality (see chapter [4 Checking that the phone works with Android](#checking-that-the-phone-works-with-android))
Chapter number removed.

2023-03-13 07:46 UTC, jovirkku commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +4. Run the Emma tool. A view similar to that in Picture 3a should appear. It shows the phone model on the left.
Oh boy. I did not realize this is possible. And I have added trillions of pictures to other docs with verbal links to them. Sigh.

2023-03-13 07:49 UTC, vigejolla commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +4. Run the Emma tool. A view similar to that in Picture 3a should appear. It shows the phone model on the left.
I know, I have been reviewing those. I'd say about 99% of cases the picture is right next to the text, so adding a link is not really necessary. Here the picture is a bit further away, so adding a link would be a bigger improvement.

2023-03-13 07:57 UTC, jovirkku commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +    Picture 3a: Initial view of Emma. Xperia 10 II connected.
The picture numbering was the same as the chapter numbering. But I'll change it.

2023-03-13 08:35 UTC, jovirkku commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +_[1] This Android 9 version appears to sometimes get an invalid WiFi MAC which prevents the phone from using WiFi networks (in the Android mode). In such a case, first flash an Android 8 version, boo
Footnotes applied.

2023-03-13 08:35 UTC, jovirkku commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +As of March 2023, the latest services were as below but note that the exact version ID's can vary by model (regular/Plus/Ultra) and by sales area. The first part of the ID (in bold letters) is signif
Language improved.

2023-03-13 10:57 UTC, vigejolla commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +As of March 2023, the latest services were as below but note that the exact version ID's can vary by model (regular/Plus/Ultra) and by sales area. The first part of the ID (in bold letters) is signif
Now there's an extra full stop at the end

2023-03-13 10:58 UTC, vigejolla commented
> All reported issues fixed (afaics). How does it look now?

Almost there. At least in my opinion - of course it's possible that JP finds something else :)

2023-03-13 11:34 UTC, jpwalden approved these changes
Looks good to me, but if you are fixing that one extra full stop then I would propose that on line 165: Should you get a "403 permission denied error" when trying to download,
 would be changed to: If you get a "403....

2023-03-13 12:12 UTC, jovirkku commented
Done.

2023-03-13 13:20 UTC, jovirkku commented on Support/Help_Articles/Reinstalling_Sailfish_OS/README.md
> +As of March 2023, the latest services were as below but note that the exact version ID's can vary by model (regular/Plus/Ultra) and by sales area. The first part of the ID (in bold letters) is signif
Removed.

2023-03-13 13:43 UTC, jovirkku commented
I have no more fixes.

2023-03-14 05:29 UTC, vigejolla approved these changes

2023-03-14 05:30 UTC, merged