Create Setting up a Sailfish Phone document
sailfishos/docs.sailfishos.org pull request #289
Opened 2023-03-15 08:15 UTC by jpwalden

2023-03-16 08:13 UTC, jovirkku commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +This document is an tutorial for Sailfish OS setup. Precondition is that the SFOS device is flashed and after the steps described below the the device is fully set up.
Split it into two sentences, please (or else it feels as if "after" were a precondition):
The precondition is that the SFOS device is flashed. After the steps described below, the device is fully set up.

2023-03-16 08:14 UTC, jovirkku commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +2. SIgn in using your Jolla Account registered above.
Sign in

2023-03-16 08:20 UTC, jovirkku commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +5. Sign in as an existing user ("I have a Jolla account") to your [Jolla account](Accounts_Setup/Setup_Jolla_Account/) registered above
Should we put this differently? It is now as if the user would sign in to the account document. How about:
Sign in as an existing user ("...") to your Jolla account registered above. Please learn more about the account by reading [this document](Accounts_Setup/Setup_Jolla_Account/)

2023-03-16 08:21 UTC, jovirkku commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +7. Select your apps
Maybe: Select the apps you want to have installed.

2023-03-16 08:26 UTC, jovirkku commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +* Nextcloud
We do not have any guidance for this account. Should we leave it out or just say "in Settings > Accounts > Add new > Nextcloud"?

2023-03-16 08:29 UTC, jovirkku commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +* Aurora Store
Let's check with Raine if we want to advertise this. It would be a very useful app store.
Easy to install from F-Droid.

2023-03-16 08:30 UTC, jovirkku commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +
I wonder if we should add here:
"Install some popular Android apps, for instance:"

2023-03-16 08:31 UTC, jovirkku commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +
Perhaps: "Sign in to your accounts that you want to use on this Sailfish device."

2023-03-16 09:53 UTC, jpwalden commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +This document is an tutorial for Sailfish OS setup. Precondition is that the SFOS device is flashed and after the steps described below the the device is fully set up.
splitted

2023-03-16 09:53 UTC, jpwalden commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +2. SIgn in using your Jolla Account registered above.
fixed

2023-03-16 09:53 UTC, jpwalden commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +5. Sign in as an existing user ("I have a Jolla account") to your [Jolla account](Accounts_Setup/Setup_Jolla_Account/) registered above
edited

2023-03-16 09:54 UTC, jpwalden commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +7. Select your apps
edited

2023-03-16 09:54 UTC, jpwalden commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +* Nextcloud
good idea, edited

2023-03-16 09:54 UTC, jpwalden commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +
edited

2023-03-16 09:55 UTC, jpwalden commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +
edited, thanks for the good comments!

2023-03-20 11:07 UTC, vigejolla requested changes
Better check all links, it's possible I missed some

2023-03-20 11:07 UTC, vigejolla commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +5. Sign in as an existing user ("I have a Jolla account") to your Jolla account registered above. Please learn more about the Jolla account from [this document](Accounts_Setup/Setup_Jolla_Account/).
I don't really like these "this document" links. The sentence structure feels clumsy. It would also be nice to know a little bit about the link before clicking. Please consider something like "We have a [separate document about the Jolla Account](/Support/Help_Articles/Accounts_Setup/Setup_Jolla_Account)".

2023-03-20 11:07 UTC, vigejolla commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +* Google, adding the Google account to your device is described [here](/Accounts_Setup/Setup_Google_Account/)
```suggestion
* Google, adding the Google account to your device is described [here](/Support/Help_Articles/Accounts_Setup/Setup_Google_Account)
```

2023-03-20 11:07 UTC, vigejolla commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +The SailfishOS operating system of Jolla supports Android apps that are featured in the Jolla Store and in Jolla-certified app partner stores. More information can be found from [here](/Android_App_S
```suggestion
The SailfishOS operating system of Jolla supports Android apps that are featured in the Jolla Store and in Jolla-certified app partner stores. More information can be found from [here](/Support/Help_Articles/Android_App_Support/#installing-applications-from-application-stores)
```

2023-03-20 11:07 UTC, vigejolla commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +* [WhatsApp](/Whatsapp_Setup/)
```suggestion
* [WhatsApp](/Support/Help_Articles/Whatsapp_Setup)
```

2023-03-20 11:54 UTC, jpwalden commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +1. Sailfish OS licence can be purchased from [Jolla Shop](/https://shop.jolla.com/)
Thanks, corrected

2023-03-20 11:54 UTC, jpwalden commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +5. Sign in as an existing user ("I have a Jolla account") to your Jolla account registered above. Please learn more about the Jolla account from [this document](Accounts_Setup/Setup_Jolla_Account/).
Ok, thanks for the comment, edited

2023-03-20 11:55 UTC, jpwalden commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +The SailfishOS operating system of Jolla supports Android apps that are featured in the Jolla Store and in Jolla-certified app partner stores. More information can be found from [here](/Android_App_S
Fixed

2023-03-20 11:56 UTC, jpwalden commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +* [WhatsApp](/Whatsapp_Setup/)
Thanks, went through links, those should be now all fixed.

2023-03-21 07:40 UTC, jovirkku requested changes

2023-03-21 07:47 UTC, jpwalden commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +* Aurora Store
Added

2023-03-21 07:48 UTC, jpwalden commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +
Thanks, added

2023-03-21 09:47 UTC, jovirkku commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +* Test input
A typo here:  Test > Text

2023-03-21 09:56 UTC, jpwalden commented on Support/Help_Articles/Setting_up_a_Sailfish_Phone/README.md
> +* Test input
Fixed

2023-03-22 07:41 UTC, jovirkku commented
I have read the current document at https://github.com/jpwalden/docs.sailfishos.org/tree/Setting_up_a_Sailfish_Phone_JB60318/Support/Help_Articles/Setting_up_a_Sailfish_Phone, again. It is a concise description of how to set up a Sailfish OS phone and contains several links to further information in other documents. This document should be detailed enough for a technically trained person to set up a Sailfish OS phone.

2023-03-22 08:41 UTC, vigejolla approved these changes

2023-03-22 08:41 UTC, merged