Document Backup Accounts
sailfishos/docs.sailfishos.org pull request #302
Opened 2023-03-24 11:56 UTC by vigejolla

2023-03-28 07:38 UTC, rainemak requested changes
Minor remarks added. Please give a look.

2023-03-28 07:38 UTC, rainemak commented on Reference/Core_Areas_and_APIs/Apps_and_MW/Accounts_and_SSO/Backup_Accounts/README.md
> +Backup accounts are implemented as [Buteo client plugins](/Reference/Core_Areas_and_APIs/Apps_and_MW/Synchronization/#buteo-client-plugins). The plugin On the Accounts and SSO side, the plugin [provi
I'd put emphasis here that backup accounts are always online accounts. Triggering a backup to an sdcard doesn't require backup account.

2023-03-28 07:43 UTC, vigejolla commented on Reference/Core_Areas_and_APIs/Apps_and_MW/Accounts_and_SSO/Backup_Accounts/README.md
> +The [sync profiles](/Reference/Core_Areas_and_APIs/Apps_and_MW/Synchronization/#sync-profiles) for the backup accounts are created by the Backup settings UI. There are three profiles for each provide
> * Backup settings ui is vague definition as same account can be created from Settings -> Accounts and Settings -> System -> Backup

That's what I was referring to. But I guess it's vague if you thought I was referring to something else -> I'll specify more clearly what is meant.

2023-03-28 10:27 UTC, vigejolla commented on Reference/Core_Areas_and_APIs/Apps_and_MW/Accounts_and_SSO/Backup_Accounts/README.md
> +Backup accounts are implemented as [Buteo client plugins](/Reference/Core_Areas_and_APIs/Apps_and_MW/Synchronization/#buteo-client-plugins). The plugin On the Accounts and SSO side, the plugin [provi
Removed extra "The plugin", added emphasis.

2023-04-03 10:45 UTC, rainemak approved these changes

2023-04-03 11:46 UTC, merged