Updating Calendar document
sailfishos/docs.sailfishos.org pull request #320
Opened 2023-04-12 13:36 UTC by jpwalden

Added how to heal google sync -chapter, added weekly view and made some other updates as well.

2023-04-12 13:58 UTC, jovirkku commented
If we wanted, line 26 could also tell that the dot colours denote various sub-calendars. The colours can be changed in the "Manage calendars" of the pulley menu.

2023-04-12 14:02 UTC, jovirkku commented on Support/Help_Articles/Calendar/README.md
> +* In the weekly view, it is easier to see the summary of the week's events.
Even better if you turn the device to the landscape position.

2023-04-12 14:36 UTC, jovirkku commented on Support/Help_Articles/Calendar/README.md
> +1. You will need the Developer mode and the SSH password. Do as instructed in this help article.
Link to the document missing?

2023-04-12 14:39 UTC, jovirkku requested changes
The modified parts (which are under review) are almost ok. Little needs be reworked.

If we want to improve the unmodified parts (unmodified by this commit) then there is more to do.

2023-04-13 07:32 UTC, jpwalden commented
> As I started reading the rich view of the whole doc (not just the changed parts) I noticed the following slight problems - the implementation of the app has changed over the years but the document text not so much...
> 
> If we wanted, line 26 (or line 28) could also tell that the dot colours denote various sub-calendars. The colours can be changed as explained in chapter "Changing calendar colours"
> 
> On the old line 56 or the new line 68, just under "_Creating a new Event in Calendar_", the sentence claims that new events should be created in the Month view. But they can be created in the week and day views, too. All 3 views share the same pulley menu. So, the sentence could be something like: "_When it’s time to mark something important down, pull down “Create new event”_.
> 
> Remove the last part of the sentence, i.e. " _where it shows what you chose for the date or time._" from line 74/86 (end of step 4). Namely, the current OS version has the Accept button in the top right corner. It does not show the selected date or time there.
> 
> Line 77/89: I do not think we have the "read-only" tagging anymore. Do we? If not, the "please note" sentence (2) should be removed. Line 113/125 refers to "read-only", too. I wonder if it is correct. Would Pekka know?

Good observations, following changes made: colours mentioned, fixed the create event part, since that can be indeed done also from weekly and daily view, removed the last part of the sentence in step4. Checked from Pekka that read-only events part is still valid, so didn't remove that.

2023-04-13 07:32 UTC, jpwalden commented on Support/Help_Articles/Calendar/README.md
> +* In the weekly view, it is easier to see the summary of the week's events.
Added comment about landscape

2023-04-13 07:32 UTC, jpwalden commented on Support/Help_Articles/Calendar/README.md
> +* You can access the day view from the left top corner by selecting the weekly view (icon in the right).
Fixed

2023-04-13 07:33 UTC, jpwalden commented on Support/Help_Articles/Calendar/README.md
> +* If you set an end date for your calendar entry, the event will end on the date you’ve specified, but the calendar will treat it as a non-stop event. This means that an event will begin the date you
That is quite unclear sentence, seems to cause more confusion than clarification, so removed it.

2023-04-13 07:33 UTC, jpwalden commented on Support/Help_Articles/Calendar/README.md
> +1. You will need the Developer mode and the SSH password. Do as instructed in this help article.
Thanks, that was missing -> added.

2023-04-13 10:35 UTC, jovirkku approved these changes
This looks ok now. 

[at new line 68, step 5, selecting the calendar: I think it is still so that the calendar once selected for an event cannot later be changed anymore - so if one mistakenly selects a wrong calendar then he should open a new event to force it to another calendar]

2023-04-13 13:23 UTC, jpwalden commented
> This looks ok now.
> 
> [at new line 68, step 5, selecting the calendar: I think it is still so that the calendar once selected for an event cannot later be changed anymore - so if one mistakenly selects a wrong calendar then he should open a new event to force it to another calendar]

Added a note about that as discussed

2023-04-13 13:30 UTC, jovirkku commented
Thanks for the "Added a note about that as discussed"

>

2023-04-13 13:31 UTC, jovirkku commented
I was supposed to say that this is a good document now. Ready to be approved.

2023-04-14 04:19 UTC, vigejolla approved these changes

2023-04-14 04:19 UTC, merged