Create Collect Location Services Logs document
sailfishos/docs.sailfishos.org pull request #337
Opened 2023-04-26 10:03 UTC by jpwalden

Location services logging document created, tested the described flow and worked ok.

2023-04-26 11:12 UTC, jovirkku commented on Support/Help_Articles/Collecting_Logs/Collect_Location_Services_Logs/README.md
> +4. To enable the GNSS logging, create the file /var/lib/environment/nemo/qtlogging.conf with the following command:
"Create the file....with the following command".
The command does not create any file. Instead, that command must be included in the conf file. The phrase looks unclear to me. I would change the text (once written by me?) to something like this:
"To enable the GNSS logging, create file /var/lib/environment/nemo/qtlogging.conf and include the following command in that file".

2023-04-26 11:12 UTC, jovirkku commented on Support/Help_Articles/Collecting_Logs/Collect_Location_Services_Logs/README.md
> +After these steps you have an journal log which includes location related logs. This can be verified by opening the journal log and checking that there are lines with the phrase "geoclue-hybris".
We could add the following sentence if you see it feasible (not mandatory, though)

This can be easily done with the command:
cat journal-geoclue.txt | grep geoclue-hybris

2023-04-26 11:16 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_Location_Services_Logs/README.md
> +After these steps you have an journal log which includes location related logs. This can be verified by opening the journal log and checking that there are lines with the phrase "geoclue-hybris".
> We could add the following sentence if you see it feasible (not mandatory, though)
> 
> This can be easily done with the command: cat journal-geoclue.txt | grep geoclue-hybris

nitpick: Useless use of cat. `grep geoclue-hybris journal-geoclue.txt` works just as well.

2023-04-26 12:13 UTC, jovirkku commented on Support/Help_Articles/Collecting_Logs/Collect_Location_Services_Logs/README.md
> +After these steps you have an journal log which includes location related logs. This can be verified by opening the journal log and checking that there are lines with the phrase "geoclue-hybris".
I like cats!

2023-04-27 04:55 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_Location_Services_Logs/README.md
> +After these steps you have an journal log which includes location related logs. This can be verified by opening the journal log and checking that there are lines with the phrase "geoclue-hybris".
Me too, that's why I don't want them to be used for unnecessary work :)

2023-04-27 07:32 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Location_Services_Logs/README.md
> +4. To enable the GNSS logging, create the file /var/lib/environment/nemo/qtlogging.conf with the following command:
Modified that a bit: "To enable the GNSS logging, modify /var/lib/environment/nemo/qtlogging.conf with the following command:
: QT_LOGGING_RULES="geoclue.provider.*=true"
I guess that is ok?

2023-04-27 07:34 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Location_Services_Logs/README.md
> +After these steps you have an journal log which includes location related logs. This can be verified by opening the journal log and checking that there are lines with the phrase "geoclue-hybris".
Thanks for the tips, added some of those, however I assume that also this would be ok: QT_LOGGING_RULES="geoclue.provider.*=false ?

2023-04-27 08:11 UTC, jovirkku commented on Support/Help_Articles/Collecting_Logs/Collect_Location_Services_Logs/README.md
> +After these steps you have an journal log which includes location related logs. This can be verified by opening the journal log and checking that there are lines with the phrase "geoclue-hybris".
Have you tested that "false" works? Why should it be false and not true? "true" I have tested and it works.
I have no idea how the logging tool uses that variable.

2023-04-27 09:00 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Location_Services_Logs/README.md
> +After these steps you have an journal log which includes location related logs. This can be verified by opening the journal log and checking that there are lines with the phrase "geoclue-hybris".
I'll modify the instructions as discussed, I'll send a new update soonish

2023-04-27 09:14 UTC, vigejolla requested changes

2023-04-27 09:14 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_Location_Services_Logs/README.md
> +Commonly used satellites: GPS, Glonass, Galileo, Beidou.
On the rendered page there is no line break betweek "System" and "Commonly", so this looks a bit funny

2023-04-27 09:14 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_Location_Services_Logs/README.md
> +reboot
Now you are only setting the environment variable for the current session, so it does not have any effect after reboot.

Best would be to remove or comment out the line from qtlogging.conf.

2023-04-27 10:07 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Location_Services_Logs/README.md
> +Commonly used satellites: GPS, Glonass, Galileo, Beidou.
True, fixed.

2023-04-27 10:08 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Location_Services_Logs/README.md
> +reboot
True, edited so that the qtlogging.conf will be removed since it is no longer needed.

2023-04-27 10:08 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Location_Services_Logs/README.md
> +After these steps you have an journal log which includes location related logs. This can be verified by opening the journal log and checking that there are lines with the phrase "geoclue-hybris".
Edited so that it is clearer that the qtlogging.conf also needs to be added and modified.

2023-04-27 10:14 UTC, vigejolla approved these changes
LGTM

2023-04-27 10:15 UTC, merged