Create SMS Logs document
sailfishos/docs.sailfishos.org pull request #342
Opened 2023-05-04 07:16 UTC by jpwalden

2023-05-04 12:14 UTC, jovirkku commented on Support/Help_Articles/Collecting_Logs/Collect_SMS_Logs/README.md
> +* Install the oFono Logger application from Jolla Store.
Add link /Support/Help_Articles/Collecting_Logs/Collect_oFono_Logs/ here. Installing oFono Logger is different on different devices.

2023-05-04 12:19 UTC, jovirkku commented on Support/Help_Articles/Collecting_Logs/Collect_SMS_Logs/README.md
> +* Please send the log files logcat.txt, journal.txt and ofono_*.tar.gz  from $HOME/Documents to Jolla for analysis. Mention the time of device when the problem happened.
Please find the log files logcat. txt and journal.txt in $HOME and ofono_*.tar.gz in $HOME/Documents. If you send them for analysis mention the exact time when the problem happened.

2023-05-04 12:47 UTC, jovirkku commented on Support/Help_Articles/Collecting_Logs/Collect_SMS_Logs/README.md
> +	devel-su
This is on line 53 already. It seems that there was no reason to exit the root mode in the meanwhile, so we can probably leave this deve-su out.

2023-05-04 12:59 UTC, jovirkku requested changes
Looks good to me. 
But I proposed some small changes.

2023-05-04 13:12 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_SMS_Logs/README.md
> +* Install the oFono Logger application from Jolla Store.
Good point, link is there below, but makes sense to add it there as well > added.

2023-05-04 13:13 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_SMS_Logs/README.md
> +	devel-su
Valid point > removed

2023-05-04 14:18 UTC, jovirkku approved these changes

2023-05-04 14:18 UTC, jovirkku commented on Support/Help_Articles/Collecting_Logs/Collect_SMS_Logs/README.md
> +* Please find the log files logcat. txt and journal.txt in $HOME and ofono_*.tar.gz in $HOME/Documents. Let's package the 3 log files into a container:
I forgot to remove this sentence: " Please find the log files logcat. txt and journal.txt in $HOME and ofono_*.tar.gz in $HOME/Documents. ".  I think it is unnecessary now that we use the tar command (it does the finding for the user).

2023-05-05 05:07 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_SMS_Logs/README.md
> +* Please find the log files logcat. txt and journal.txt in $HOME and ofono_*.tar.gz in $HOME/Documents. Let's package the 3 log files into a container:
Thanks, true -that is not needed anymore > removed.

2023-05-05 05:31 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_SMS_Logs/README.md
> +* Install the oFono Logger application from Jolla Store.
Well, `pkcon install sailfish-log-viewer-ofono` works on all devices. But the link is good.

2023-05-05 05:38 UTC, vigejolla approved these changes
LGTM

2023-05-05 05:38 UTC, merged