Updating Storage Space document
sailfishos/docs.sailfishos.org pull request #351
Opened 2023-05-12 07:49 UTC by jpwalden

Added How to check the big disc space consumers -documents content to Storage Space -document.

2023-05-12 10:01 UTC, vigejolla requested changes

2023-05-12 10:01 UTC, vigejolla commented on Support/Help_Articles/Storage_Space/README.md
> +rpm -qa --queryformat '%{SIZE}\t %{NAME}-%{version}\n' | sort -nr | more
I kind of have a feeling that we should have some kind of warning here, along the lines of "Please note that removing packages can break your system if you don't know what you are doing". Or something.

2023-05-12 11:20 UTC, jpwalden commented on Support/Help_Articles/Storage_Space/README.md
> +A more fine-grained listing, both from the root and from home:
Yes, you are right. Changed the order since makes sense to check the high-level list first and after that if needed the full list.

2023-05-12 11:22 UTC, jpwalden commented on Support/Help_Articles/Storage_Space/README.md
> +rpm -qa --queryformat '%{SIZE}\t %{NAME}-%{version}\n' | sort -nr | more
Valid point, added a warning.

2023-05-15 04:32 UTC, vigejolla approved these changes

2023-05-15 04:32 UTC, merged