Update instructions with fixes and workaround
sailfishos/docs.sailfishos.org pull request #36
Opened 2022-02-07 08:30 UTC by llewelld

When following these instructions I hit some practical issues:

1. Couldn't gain `sudo` in the Ubuntu Chroot.
2. `repo` command missing.
3. Failed build dependency `pkgconfig(audiosystem-passthrough)`.
4. Errors when applying patches.
5. Missing commands for building droid-hal etc.

I've added some suggested changes for working around the errors or explaining that the errors can be ignored.

2022-02-07 09:19 UTC, Thaodan commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +
Repo should be installed with the distros pkg manager.

2022-02-07 09:20 UTC, Thaodan commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +
Create a PR to the pkg.

2022-02-07 09:22 UTC, Thaodan commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +
Read  HADK chapter 5.1 -> https://source.android.com/setup/develop#installing-repo

2022-02-07 09:25 UTC, llewelld commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +
```
flypig@plechelm:~$ lsb_release -d
Description:    Ubuntu 20.04.3 LTS
flypig@plechelm:~$ sudo apt install repo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package repo
```

I could reword this part to just recommend following [Google's instructions](https://source.android.com/setup/develop#installing-repo) here, as is done in the HADK?

2022-02-07 09:46 UTC, sledges commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +
There is no problem with the packaging. It's due to audiosystem-passthrough-devel not available in 4.3.0 repos yet.

I forgot to add it here, so please do for me:)
````diff
 # Remove the next two lines when a new SFOS release comes out (one after 4.3.0):
 rpm/dhd/helpers/build_packages.sh --mw=https://github.com/mer-hybris/libgbinder.git
 rpm/dhd/helpers/build_packages.sh --mw=https://github.com/sailfishos/sensorfw.git --spec=rpm/sensorfw- qt5-binder.spec
+rpm/dhd/helpers/build_packages.sh --mw=https://github.com/mer-hybris/audiosystem-passthrough.git
```

2022-02-07 09:51 UTC, Thaodan commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +
> I could reword this part to just recommend following [Google's instructions](https://source.android.com/setup/develop#installing-repo) here, as is done in the HADK?

I would copy the line from HADK into here or refactor the HADK chapter to be more about just setting the dev environment and then telling the user to read it. 
E.g. Read chapter 5.1 setting up your environment.

2022-02-07 10:04 UTC, sledges commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +rpm/dhd/helpers/build_packages.sh --gg
All of these have already been executed in the above instructions, no need to rebuild any of those again.

2022-02-07 10:08 UTC, sledges commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +```
Such fix should go to the HADK pdf instead, to benefit all porters.

2022-02-07 10:12 UTC, llewelld commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +rpm/dhd/helpers/build_packages.sh --gg
Just following the instructions I got the following errors:
```
PlatformSDK flypig@plechelm:~/hadk$ rpm/dhd/helpers/build_packages.sh --version
* Building rpm/droid-hal-version-xqbt52.spec 
        droid-config is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        droid-config-preinit-plugins is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        droid-config-pulseaudio-settings is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        droid-config-sailfish is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        droid-config-xqbt52 is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        droid-config-xqbt52-flashing is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        droid-config-xqbt52-preinit-plugin is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        droid-config-xqbt52-pulseaudio-settings is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        droid-config-xqbt52-sailfish is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        droid-hal is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        droid-hal-pdx213 is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        droid-hal-pdx213-img-boot is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        droid-hal-pdx213-img-recovery is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        ngfd-plugin-native-vibrator is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        qt5-feedback-haptics-native-vibrator is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
        qtscenegraph-adaptation is needed by droid-hal-version-xqbt52-0.0.1-202202070713.aarch64
Building target platforms: aarch64-meego-linux-gnu
Building for target aarch64-meego-linux-gnu
No journal files were found.
Failed to seek to cursor: Invalid argument
* Check /home/flypig/hadk/hybris/droid-hal-version-xqbt52.log for full log. 
!! building of package failed 
```

2022-02-07 10:23 UTC, sledges commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +rpm/dhd/helpers/build_packages.sh --gg
You've already run [--droid-hal](https://github.com/sailfishos/docs.sailfishos.org/blob/b3e11510e455b1d1d57e0576bd9cb31bbc5e7f4e/Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md?plain=1#L88) and [--configs](https://github.com/sailfishos/docs.sailfishos.org/blob/b3e11510e455b1d1d57e0576bd9cb31bbc5e7f4e/Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md?plain=1#L96). I bet the latter failed (due to ofono-binder-plugin pattern problem), hence-why eventual failures in any subsequent commands should be expected.

2022-02-07 10:35 UTC, sledges commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +rpm/dhd/helpers/build_packages.sh --gg
Ok, --configs won't fail due to wrong pattern, it's the mic that will fail. But still there is no need to rebuild everything again at  the end:)

2022-02-07 10:36 UTC, sledges commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +rpm/dhd/helpers/build_packages.sh --gg
The failing of --version means a problem is somewhere else. Will inspect your logs.

2022-02-07 12:03 UTC, llewelld commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +```
I've submitted a PR to the HADK for this and will remove it from here.

2022-02-08 12:10 UTC, Thaodan commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +```
Please move mounting of android images to platform sdk no changes needed on the ubuntu changeroot.

2022-02-08 12:12 UTC, sledges commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +```
There are many more places that use sudo, not only android images.

2022-02-08 15:48 UTC, Thaodan commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +```
The only place that should need sudo (for steps that need to be done inside the habuild sdk) is the call to apt-get since the rest could be also done inside the platfrom sdk but I guess that's just preference.

But you are right, I'd just like to fix the underlying issue instead.

2022-02-09 07:27 UTC, Thaodan commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +```
Found the source of the bug:
https://github.com/sailfishos/android-tools-hadk/pull/6

2022-02-09 07:34 UTC, Thaodan commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +
> I could reword this part to just recommend following [Google's instructions](https://source.android.com/setup/develop#installing-repo) here, as is done in the HADK?

Why do we need to copy google's instructions into the guide?  The user can just follow the link and read the instructions there.

2022-02-09 07:35 UTC, Thaodan commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +
> ```
> flypig@plechelm:~$ lsb_release -d
> Description:    Ubuntu 20.04.3 LTS
> flypig@plechelm:~$ sudo apt install repo
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package repo
> ```
> 

Section 1 on the Google's instructions: "If those commands didn’t work for your system–for example, you see that the package version is outdated, or there isn’t an official package available from your Linux distribution, manually install Repo using the following commands"

2022-02-09 11:36 UTC, sledges commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +
> > I could reword this part to just recommend following [Google's instructions](https://source.android.com/setup/develop#installing-repo) here, as is done in the HADK?
> 
> Why do we need to copy google's instructions into the guide?

Rewording is not copying. He meant to just write what's in the HADK pdf:
> You also need to install the repo command from the AOSP source code repositories, see [Installing repo](https://source.android.com/setup/develop#installing-repo).

2022-02-09 11:39 UTC, sledges commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +
This will be fixed by or related to https://github.com/mer-hybris/droid-hal-device/pull/320.
So please remove this snippet from your PR:
```
# Install audiosystem-passthrough
# FIXME: Remove this workaround for pkgconfig(audiosystem-passthrough) error once it's fixed in the spec
sb2 -R -m sdk-install -t $VENDOR-$DEVICE-aarch64.default zypper install audiosystem-passthrough
```

2022-02-09 11:39 UTC, sledges commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +rpm/dhd/helpers/build_packages.sh --gg
Please remove these duplicates:)

2022-02-09 11:40 UTC, sledges commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +```
Please remove as this goes to HADK pdf until the above fix is released to public.

2022-02-09 13:36 UTC, llewelld commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +
Text updated.

2022-02-09 13:36 UTC, llewelld commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +
Removed.

2022-02-09 13:39 UTC, llewelld commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +rpm/dhd/helpers/build_packages.sh --gg
Removed; the underlying issue will be fixed in the next release as I understand it.

2022-02-09 13:42 UTC, llewelld commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +```
Removed, proposed to the HADK and if I understand correctly the underlying issue has been properly [fixed by @Thaodan](https://github.com/sailfishos/android-tools-hadk/pull/6).

2022-02-09 13:44 UTC, llewelld commented
Rebased; commit title and summary updated.

2022-02-09 14:38 UTC, sledges requested changes
Please move bug#ref from commit message (subject) to anywhere as stand-alone in the commit [description](https://github.com/sailfishos/docs.sailfishos.org/blob/master/README.md#review-guidelines).

2022-02-09 15:12 UTC, Thaodan requested changes
The text looks good to me however the commit message is over 80 character wide I  don't think that's good.

2022-02-09 15:29 UTC, llewelld commented
> The text looks good to me however the commit message is over 80 character wide I don't think that's good.

It's not so uncommon in this repo.
```
$ git log --oneline | grep -E ".{88,}" | wc -l
53
```

2022-02-09 15:44 UTC, martyone commented
There is upstream history (e842498) which really contains long summaries, but our own commits are all under 80 :)

2022-02-10 07:19 UTC, sledges approved these changes

2022-02-10 07:37 UTC, merged