Create Collect Synchronization Logs document
sailfishos/docs.sailfishos.org pull request #364
Opened 2023-05-31 10:22 UTC by jpwalden

Creating of collect synchronization logs document

2023-05-31 11:16 UTC, vigejolla requested changes
couple of issues

2023-05-31 11:16 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +1. Preparations: do as instructed in the [Prepare for collecting journal chapter](#prepare-for-collecting-logs) above.
```suggestion
1. Preparations: do as instructed in the [Prepare for collecting journal chapter](#prepare-for-collecting-journal) above. 
```

2023-05-31 11:16 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +5. Use <ctrl>C to stop the previous command.
```suggestion
5. Use \<ctrl\>C to stop the previous command.
```

2023-05-31 11:16 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +3. Trigger a sync cycle by opening up "Settings > Accounts". Then long-press either the account you want to debug. Tap Sync in the pop-up menu.
Same "either - or" thing here

2023-05-31 11:16 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +1. Preparations: do as instructed in the [Prepare for collecting journal chapter](#prepare-for-collecting-logs) above.
Same broken link as above

2023-05-31 12:48 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +## PREPARE FOR COLLECTING JOURNAL
Thanks, missed that one -fixed

2023-05-31 12:48 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +* [CalDAV and CardDAV Community Contributions Sync Logs chapter](https://sailfishos.org/wiki/CalDAV_and_CardDAV_Community_Contributions/#sync-logs)
Fixed

2023-05-31 12:48 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +* [Sailfish OS Cheat Sheet's Diagnostics chapter](https://sailfishos.org/wiki/Sailfish_OS_Cheat_Sheet#Diagnostics)
Thanks -fixed

2023-05-31 12:49 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +
Valid point -added

2023-05-31 12:49 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +NOTE: We will revert this configuration to its original status in [this chapter](#reverting-the-device-to-original-configuation) below.
fixed

2023-05-31 12:49 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +5. Use <ctrl>C to stop the previous command.
Thanks, yes -that is needed. Fixed.

2023-05-31 12:49 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +1. Preparations: do as instructed in the [Prepare for collecting journal chapter](#prepare-for-collecting-logs) above.
Fixed

2023-05-31 12:49 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +5. Use <ctrl>C to stop the previous command.
Thanks, yes -that is needed. Fixed.

2023-05-31 12:50 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +3. Trigger a sync cycle by opening up "Settings > Accounts". Then long-press either the account you want to debug. Tap Sync in the pop-up menu.
Edited the text, it sounded odd -thanks.

2023-05-31 12:50 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +1. Preparations: do as instructed in the [Prepare for collecting journal chapter](#prepare-for-collecting-logs) above.
Fixed

2023-06-01 06:22 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +NOTE: We will revert this configuration to its original status in [this chapter](#reverting-the-device-to-original-configuation) below.
Nope, there is still a typo (missing 'r')

2023-06-01 06:23 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +Preparations: do as instructed in the [Prepare for collecting journal chapter](#prepare-for-collecting-logs) above.
You probably missed this one because it was hidden behind github's "show more" link...

2023-06-01 06:24 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +3. Trigger a sync cycle by opening up "Settings > Accounts". Then long-press either the account you want to debug. Tap Sync in the pop-up menu.
also this one

2023-06-01 07:25 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +NOTE: We will revert this configuration to its original status in [this chapter](#reverting-the-device-to-original-configuation) below.
True, now fixed for real

2023-06-01 07:26 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +Preparations: do as instructed in the [Prepare for collecting journal chapter](#prepare-for-collecting-logs) above.
Yes, that happened, now also this is fixed.

2023-06-01 07:27 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_Synchronization_Logs/README.md
> +3. Trigger a sync cycle by opening up "Settings > Accounts". Then long-press either the account you want to debug. Tap Sync in the pop-up menu.
Yes, now also this is fixed.

2023-06-01 07:37 UTC, vigejolla approved these changes
LGTM

2023-06-01 07:37 UTC, merged