Create Collect OS Update Failure Logs document
sailfishos/docs.sailfishos.org pull request #369
Opened 2023-06-08 11:49 UTC by jpwalden

Creating of Collect OS Update Failure Logs document

2023-06-08 12:40 UTC, vigejolla requested changes

2023-06-08 12:40 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_OS_Update_Failure_Logs/README.md
> +Let's define a variable for your home area first:
I think we could provide additional reasoning here. A new variable is needed because $HOME points to /root after `devel-su`.

2023-06-08 12:40 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_OS_Update_Failure_Logs/README.md
> +### Your device is failing to boot up further than to Sailfish logo
Are you sure these instructions work these days? To me they look a lot like something that would have worked on Jolla 1...

2023-06-15 11:42 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_OS_Update_Failure_Logs/README.md
> +Let's define a variable for your home area first:
Ok -thanks, added some comments.

2023-06-15 11:44 UTC, jpwalden commented on Support/Help_Articles/Collecting_Logs/Collect_OS_Update_Failure_Logs/README.md
> +### Your device is failing to boot up further than to Sailfish logo
Tested with X10 III and those do work, however later part didn't seem to be valid anymore so decided to remove that.

2023-06-20 05:52 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_OS_Update_Failure_Logs/README.md
> +## Your device is failing to boot up
Two comments: 1) I think this headline should be on the same level as the "Your device can still be booted..." headline below, i.e. with `###`
2) I think the order of chapters is a bit weird. I think it would make sense to move this chapter so that it would be after the "Your device can still be booted..." chapter. Well, I might be wrong, but perhaps you could try it if it makes sense to you.

2023-06-20 09:33 UTC, vigejolla commented on Support/Help_Articles/Collecting_Logs/Collect_OS_Update_Failure_Logs/README.md
> +## Your device is failing to boot up
A lot better now - but now after the reordering I realized that the first chapter (under the main title) and the chapter "Collecting logs of the failed update" are almost (but not 100%) identical. I think the latter one could be just removed.

2023-06-20 11:01 UTC, vigejolla approved these changes

2023-06-20 11:02 UTC, merged