Set correct indention
sailfishos/docs.sailfishos.org pull request #55
Opened 2022-03-27 21:17 UTC by pherjung

download is described as method, without indentation it's a function.

2022-03-28 05:55 UTC, martyone approved these changes

2022-04-13 08:08 UTC, llewelld requested changes
Thanks for the PR @pherjung. The changes you've suggested all look good, but I think it would make sense to fix the incorrect indentation in the few lines above at the same time, if that would be okay?

2022-04-13 08:08 UTC, llewelld commented on Develop/Apps/Tutorials/Creating_an_application_in_Python/README.md
>      self.bgthread.start()
It looks like lines 75-78 should be inside the `__init__` method and so also need additional indentation. Would it be possible to fix this at the same time please?

2022-04-13 12:34 UTC, llewelld approved these changes
Great, many thanks! This looks good to me now.

2022-04-13 13:03 UTC, merged