Update Xperia 10 III port status
sailfishos/docs.sailfishos.org pull request #57
Opened 2022-03-30 11:09 UTC by Thaodan

- Document changes done in:
  - https://github.com/mer-hybris/droid-src-sony/pull/15
- Add screen off and on workaround for camera server crashes

2022-03-30 11:31 UTC, llewelld reviewed
It would be helpful to add just a little more detail to the commit message. E.g. "Updated to reflect changes made to camera support".

2022-03-30 11:31 UTC, llewelld commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +      mode.
```suggestion
    - Sensors of tele and uwide lenses are disabled for now, this is done because they
      depend on MultiCamera which creates issues when switching between them when using
      Camera1 API mode.
```
Just a slight change of wording to make the meaning clearer.

2022-03-30 11:31 UTC, sledges requested changes
Please do not hard-wrap text, otherwise it's hard to read diffs in future when they get re-wrapped after editing.

2022-03-30 11:31 UTC, sledges commented on Develop/HW_Adaptation/Sailfish_X_Xperia_Android_11_Build_and_Flash/README.md
> +    - Need to restart Camera app or turn the screen on and off after finishing recording video, upstream bug <https://github.com/sonyxperiadev/bug_tracker/issues/761>
```suggestion
    - Sensors of tele and uwide lenses are disabled for now, because they depend on MultiCamera which creates issues when switching between front and rear in Camera1 API mode.
      Similar bug on AOSP too: <https://github.com/sonyxperiadev/bug_tracker/issues/732>
    - Need to restart Camera app or turn the screen off and on after finishing recording video, upstream bug <https://github.com/sonyxperiadev/bug_tracker/issues/761>
    - Screen brightness does not correspond slider value, also on AOSP <https://github.com/sonyxperiadev/bug_tracker/issues/764>. This causes display luminosity fluctuate when automatic brightness setting is enabled.
```

2022-03-31 06:08 UTC, llewelld approved these changes
These changes look nice and clear to me.

2022-03-31 06:59 UTC, sledges approved these changes

2022-03-31 07:36 UTC, merged