Introduce new main level quick links
sailfishos/docs.sailfishos.org pull request #68
Opened 2022-04-20 15:11 UTC by rainemak

This change introduces "Supported devices", "Releases", "User
experience", and "Forum" to the main page of the docs.

Signed-off-by: Raine Makelainen <raine.makelainen@jolla.com>

2022-04-20 15:24 UTC, llewelld approved these changes
This looks great. It might be worth adding in to the commit message about the fact you've also included an up-to-date list of all the releases, but all of my comments are super-minor, so I'm approving already.

2022-04-20 15:47 UTC, sledges requested changes
Mobile view (Sailfish OS Xperia 10 III) in landscape results in 3x2 grid followed by 1x2 (also the order is not what you expect).

Such breakage after adding more squares has always been anticipated, given how much cross-browser/mobile tailoring has been poured to this front page... Improvements welcome when time permits:)

Couple of minor suggestions below.

2022-04-20 15:47 UTC, sledges commented on index.md
> +      <br/><br/>
To align with all other paragraphs on the same line.
```suggestion
      <br/><br/><br/>
```

2022-04-21 10:25 UTC, rainemak commented on index.md
> +      <br/><br/>
Will break also User Experience into two lines and align landing-box-texts accordingly.

2022-04-21 10:39 UTC, rainemak commented
Will squash review changes after this iteration is reviewed

2022-04-21 11:28 UTC, sledges approved these changes
Layout grid now looks amazing!

However now there are paragraph spacing issues on mobile browsers (Sailfish Browser and on an older Chrome/webkit) in "Supported Devices" and "User Experience" boxes.
But can be dealt in another PR perhaps?

2022-04-21 11:37 UTC, rainemak commented
> Layout grid now looks amazing!
> 
> However now there are paragraph spacing issues on mobile browsers (Sailfish Browser and on an older Chrome/webkit) in "Supported Devices" and "User Experience" boxes. But can be dealt in another PR perhaps?

Yes, let's deal in another PR.

2022-04-21 11:39 UTC, rainemak commented
Squashed review findings into the first commit.

2022-04-21 12:19 UTC, merged