Add API Docs Contribution page
sailfishos/docs.sailfishos.org pull request #92
Opened 2022-07-11 16:02 UTC by martyone

2022-07-12 06:18 UTC, rainemak requested changes
Very nice and informative piece for documenting APIs. Added two small remarks, let's discuss those through, fix them and land this.

2022-07-12 06:18 UTC, rainemak commented on Develop/Collaborate/API_Docs_Contributions/README.md
> +The preferred way of writing API documentation for Qt-based APIs is with the help of the [QDoc](https://doc.qt.io/qt-5/qdoc-index.html) documentation tool. Its use for documenting Sailfish APIs is su
The sailfish-qdoc-template points to https://sailfishos.org/develop/docs/sailfish-components-pickers/ which is a wrong link

"Its use for documenting Sailfish APIs is supported with the [sailfish-qdoc-template](https://sailfishos.org/develop/docs/sailfish-components-pickers/) package, which also comes with essential usage notes."

I'd rephrase above sentence (with right links of course). 
```
The [QDoc](https://doc.qt.io/qt-5/qdoc-index.html) usage on Sailfish is supported with the [Sailfish QDoc template](https://sailfishos.org/develop/docs/sailfish-components-pickers/), which comes with essential usage notes.
```

2022-07-12 06:18 UTC, rainemak commented on Develop/Collaborate/API_Docs_Contributions/README.md
> +### Various tips on writing QDoc based documentation
```suggestion
### Tips on writing QDoc based documentation
```
Better without extra various.

2022-07-12 06:55 UTC, martyone commented on Develop/Collaborate/API_Docs_Contributions/README.md
> +The preferred way of writing API documentation for Qt-based APIs is with the help of the [QDoc](https://doc.qt.io/qt-5/qdoc-index.html) documentation tool. Its use for documenting Sailfish APIs is su
Updated. Did you really mean just "on Sailfish"? Without "OS" or something after "Sailfish".

2022-08-04 13:07 UTC, rainemak commented on Develop/Collaborate/API_Docs_Contributions/README.md
> +The preferred way of writing API documentation for Qt-based APIs is with the help of the [QDoc](https://doc.qt.io/qt-5/qdoc-index.html) documentation tool. Its use for documenting Sailfish APIs is su
"Sailfish OS" works better.

2022-08-04 13:08 UTC, rainemak commented on Develop/Collaborate/API_Docs_Contributions/README.md
> +The preferred way of writing API documentation for Qt-based APIs is with the help of the [QDoc](https://doc.qt.io/qt-5/qdoc-index.html) documentation tool. [QDoc](https://doc.qt.io/qt-5/qdoc-index.ht
Is https://sailfishos.org/develop/docs/sailfish-qdoc-template/ on it way as well? Currently it's 404 not found.

2022-08-04 13:18 UTC, martyone commented on Develop/Collaborate/API_Docs_Contributions/README.md
> +The preferred way of writing API documentation for Qt-based APIs is with the help of the [QDoc](https://doc.qt.io/qt-5/qdoc-index.html) documentation tool. [QDoc](https://doc.qt.io/qt-5/qdoc-index.ht
yes, jb#58373

2022-08-05 08:42 UTC, rainemak approved these changes

2022-08-12 10:32 UTC, vigejolla commented on Develop/Collaborate/API_Docs_Contributions/README.md
> +Less bad example would use `https://sailfishos.org/develop/docs/foo-bar` as the URL. This would be already correct location at the time of writing this documentation, but you should also utilize the
Where is this `BASE_URL` defined?

2022-08-15 09:13 UTC, martyone commented on Develop/Collaborate/API_Docs_Contributions/README.md
> +Less bad example would use `https://sailfishos.org/develop/docs/foo-bar` as the URL. This would be already correct location at the time of writing this documentation, but you should also utilize the
https://github.com/sailfishos/sailfish-qdoc-template/blob/master/config/sailfish-qdoc-template.prf#L22

2022-08-15 09:16 UTC, martyone commented
Rebased

2022-08-15 09:17 UTC, martyone commented
To be merged after next release with sailfish-qdoc-template updated.

2022-08-16 05:13 UTC, vigejolla commented on Develop/Collaborate/API_Docs_Contributions/README.md
> +Less bad example would use `https://sailfishos.org/develop/docs/foo-bar` as the URL. This would be already correct location at the time of writing this documentation, but you should also utilize the
> https://github.com/sailfishos/sailfish-qdoc-template/blob/master/config/sailfish-qdoc-template.prf#L22

I thought it would be defined in the template, but for some reason I didn't find it. Maybe I was tired or something... nevermind :)

2023-02-28 10:53 UTC, vigejolla commented
rebased

2023-02-28 11:06 UTC, rainemak approved these changes

2023-02-28 11:07 UTC, merged