WIP: Simplify Opensource documentation
sailfishos/docs.sailfishos.org pull request #98
Opened 2022-08-15 08:53 UTC by saukko

This is not tested yet, just pushed the current draft foward.

- Simplify the open source documentation.
- Add first HowTo page
- Add HowTo about checking licenses from a device. JB#58515

Signed-off-by: Marko Saukko <marko.saukko@jolla.com>

2022-08-17 13:05 UTC, rainemak commented on Develop/Open_Source/README.md
> +In Sailfish OS we follow [Fedora's shortnames](https://fedoraproject.org/wiki/Licensing:Main#Good_Licenses) for the license names.
:+1:

2022-08-17 13:08 UTC, rainemak commented on index.md
>    <div class="clearfix"></div>
I bet that this should be the last div within the `<div class="landing-container">` i.e. move above line after `/HowTo`

2022-09-21 07:04 UTC, saukko commented on index.md
>    <div class="clearfix"></div>
I think there was one extra clearfix as copypaste in the previous, fixed now.

2022-09-21 10:26 UTC, rainemak approved these changes
LGTM. Let's take this as a starting point.

2022-09-21 10:37 UTC, vigejolla requested changes

2022-09-21 10:37 UTC, vigejolla commented on Develop/Open_Source/README.md
> +The various open source components have different licenses depending on the licensing decision by the upstream maintainers. Sailfish OS respects these license requirements, which can also be [read fr
The link does not work. I believe it should be [read from the device](/HowTo#check-open-source-licenses).

2022-10-14 11:30 UTC, vigejolla commented on HowTo/README.md
> +permalink: HowTo/
Wouldn't it be better to add the page under one of the existing roots (Develop, Reference, Services, Tools or Support)? If you just add a new root like this, it won't appear anywhere in the top/left menus.

2022-10-14 11:40 UTC, martyone commented on HowTo/README.md
> +permalink: HowTo/
I'd wait a bit before adding another dimension to the already entangled documentation :) This would again scatter more the information. I would prefer leading towards a more linear structure. Something that one can read through from start to end, learning gradually, not left to learn related bits separately in random order. And ensure that the search functionality yields accurate results, which should be the case if the right keywords appear in titles.

In any case, to me this looks more like a FAQ than how-to.

2022-10-14 11:54 UTC, vigejolla commented on HowTo/README.md
> +permalink: HowTo/
Maybe FAQ, or perhaps it could be considered part of the [Tips and Tricks](https://docs.sailfishos.org/Support/Help_Articles/Tips_and_Tricks/) page?

2022-10-25 08:05 UTC, rainemak commented on HowTo/README.md
> +permalink: HowTo/
@vigejolla could you please move this "HowTo" part to the "Tips and Tricks" under Help_Articles. This has been open for ages. When moving forward we can move this elsewhere if needed.

2022-10-25 08:25 UTC, rainemak approved these changes
Looks good now! Please merge.

2022-10-25 08:58 UTC, merged